### ISSUE TITLE
Make NUnit.Engine.Internal.Tests.PathUtilTests_Windows.SamePathOrUnder work under ubuntu-latest

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit-console#1026]
When migrating the azure pipelines from ubuntu-16.04 to ubuntu-latest the test `NUnit.Engine.Internal.Tests.PathUtilTests_Windows.SamePathOrUnder` started failing under `netcoreapp2.1/Linux`. For now the test has been marked to only run under "windows", but we should make this test run as before.

**Comment by CharliePoole** [comment]
We should wait to determine whether we are implementing #1026. If we do that then this issue goes away.

**Comment by mikkelbu** [comment]
> We should wait to determine whether we are implementing #1026. If we do that then this issue goes away.

I guess you mean #1045 ? But will #1045 mean that we no longer will compile and run the tests under Linux?

**Comment by CharliePoole** [comment]
@mikkelbu 
Yes! I corrected the comment.

My logic... If we no longer build NUnit.ConsoleRunner.NetCore, we no longer need a .NET Core 3.1 engine. In fact, I don't see a need for a .NET Standard 2.0 engine either, although that's probably a separate matter.

So...

If we still have a .NET Standard engine, we can test it using .NET Core 3.1 - or even .NET 5.0 or 6.0 - doesn't matter which.

If we don't have it at all, then the tests may go away.

I guess I ought to have said the issue _may_ go away. :-)

BTW, I at first thought I could easily fix this by just dropping the .NET Core 2.1 tests entirely. But when I tried, I quickly realized we would no longer be testing the .NET Standard engine at all.

**Comment by CharliePoole** [comment]
We should try to fix this and other small issues pertaining to the .NET Core runner.

**Comment by CharliePoole** [comment]
Failure is due to case differences. Apparently, when I first wrote this, I expected the test to work like windows with windows paths and like linux with linux paths. I could actually make that work but it actually seems a bit silly to me right now.

My solution for the moment is to just fix the case differences so it works. `SamePathOrUnder` is actually only used in DomainManager, which we only build for the .NET Framework, so I think we can ultimately move the code and test over there.
