### ISSUE TITLE
Unable to deduce ExtensionPoint for Type TestPlugin.TestPlugin. Specify Path on ExtensionAttribute to resolve

### ISSUE THREAD

**Issue by wafnetcore** [nunit/nunit-console#1040]
I'm writing an Extension for NUnit; which is in it's own assembly named TestPlugin.
The TestPlugin.addins file in the TestPlugin project has the  content  "TestPlugin.dll" (it's marked as content and copy always on build)
The C# code in TestPlugin.proj is this:
```C#
using NUnit.Framework.Interfaces;
using System.Collections.Generic;
using System.IO;

namespace TestPlugin
{
    [NUnit.Engine.Extensibility.Extension(EngineVersion = "3.4")]
    public class TestPlugin : ITestListener
    {
        public TestPlugin()
        {
            AppendLog("CTOR");
        }

        public void SendMessage(TestMessage message)
        {
            AppendLog($"SendMessage {message}");
        }

        public void TestFinished(ITestResult result)
        {
            AppendLog($"TestFinished {result.Test.Name}");
        }

        public void TestOutput(TestOutput output)
        {
            AppendLog($"TestOutput {output.TestName}");
        }

        public void TestStarted(ITest test)
        {
            AppendLog($"Test Started {test.Name}");
        }

        private static void AppendLog(string str)
        {
            File.AppendAllLines("../../Logs/TestPlugin.log", GetList(str));
        }

        private static List<string> GetList(string str)
        {
            return new List<string>() { str };
        }
    }
}
```

My Test Project includes the Plugin project like this:
```xml
  <ItemGroup>
    <ProjectReference Include="..\NunitPlugIn\TestPlugin.csproj" />
  </ItemGroup>
```

When I build the solution.. this is shown in the bin/Debug/netcoreapp3.1 folder of the Test Project.

![image](https://user-images.githubusercontent.com/91170766/142273731-28a7a718-8805-4920-8e79-bc7ad236629d.png)

The build always shows up with the plugin content and if I double check the .addins file it shows the correct dll in the Test project.

```
TestPlugin.dll
```
But when I run the Test and trace the output for Tests I see this:
```
[11/17/2021 1:39:09.188 PM] NUnit Adapter 3.17.0.0: Test execution started
[11/17/2021 1:39:09.358 PM] Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests
[11/17/2021 1:39:09.364 PM] Unable to deduce ExtensionPoint for Type TestPlugin.TestPlugin. Specify Path on ExtensionAttribute to resolve.
[11/17/2021 1:39:09.391 PM]    at NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(ExtensionAssembly assembly)
```
If I attempt to add the path in the plugin itself:
```
 [NUnit.Engine.Extensibility.Extension(EngineVersion = "3.4", Path ="TestPlugin.dll")]
```
The same error is issued.

I tried to find NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(ExtensionAssembly assembly)
To see why is wasn't working but could not find it.

Please advise on what I'm missing.
None of the tests run because of the error shown above.

**Comment by wafnetcore** [comment]
The TestPlugin Dependencies are:
![image](https://user-images.githubusercontent.com/91170766/142275519-a79afc42-aa38-4bd6-8a86-900071c752ca.png)



The Test Project Dependencies are:
![image](https://user-images.githubusercontent.com/91170766/142275843-b212464c-5d26-4dd9-a2a0-7fb7b251e1dd.png)
And
![image](https://user-images.githubusercontent.com/91170766/142275892-d5292b04-77ed-436a-a243-74a82e83c870.png)

**Comment by CharliePoole** [comment]
The "Path", which the engine is unable to deduce is not a path in the file system, but a (conceptual) path through the hierarchy of extension points. So, for example, the Path for the TestListener extension point is `/NUnit/Engine/TypeExtensions/ITestEventListener`. However, that's just an explanation for the particular message you got and not the real problem.

The interface you should be implementing is not `ITestListener`, which is part of the NUnit Framework, but `ITestEventListener`, which is part of the NUnit engine API. You should be referencing the api in the `NUnit.Engine.Api` package.

Your extension should __not__ reference the NUnit, NUnit.Engine or NUnit3TestAdapter packages. This will cause either visible conflicts or (even worse) hidden errors. Extensions are not supposed to know anything about their environment but to only operate based on the specific calls made to them. 

In particular, a reference to the Engine is a bad idea because you could only use it by instantiating the engine... that is, a different instance of the engine from the one that is hosting you. The API does not allow you to access that instance either, but only to do what the particular extension point is designed for.

That pretty much covers problems I noticed with your extension. Now for the question of hosting the extension.

Since your extension is an NUnit package, it will be available to the engine IFF the engine was installed as an NUnit package. For example, if you run the NUnit3 console runner installed in that way, it will automatically find the extension and use it. Any other copy of the engine and runner will only find the extension if you can manage to manually tell it where it is.

My suggestion is that you first make this work in the above environment (console runner and engine installed via nuget) and only after it works deal with the harder issue of getting it to work under the test adapter. That's basically the order in which I develop extensions.

**Comment by wafnetcore** [comment]
Charlie;
 Thanks for setting me straight...
Here's the changes (based on your advice) which now works...

The plugin folder structure and NUnit.Engine Dependency

![image](https://user-images.githubusercontent.com/91170766/142290729-4ead1ca9-27cf-4233-97bd-9fb3e908e39d.png)

The content of the TestPlugin.addins file: 
```
TestPlugin.dll
```
TestListener.cs
```cs
using NUnit.Engine;
using System.IO;

namespace TestPlugin
{
    [NUnit.Engine.Extensibility.Extension(EngineVersion = "3.4")]
    public class TestListener : ITestEventListener
    {
        public void OnTestEvent(string report)
        {
            var path = @"TestListener.log";
            var sw = File.AppendText(path);
            sw.WriteLine(report);
            sw.Close();
        }
    }
}
```


The Test Project Reference to the project above
![image](https://user-images.githubusercontent.com/91170766/142289728-bb12bbe8-00ff-4582-b59b-ce2b8ab39d0a.png)



Finally, in the Test Project's bin/debug/netcoreapp3.1 folder:

![image](https://user-images.githubusercontent.com/91170766/142290075-1c05c99b-ff9a-4d94-9728-e56d471a11db.png)

Partial Results:
![image](https://user-images.githubusercontent.com/91170766/142291520-9873e339-0ecf-43a8-af4b-e37613ebfc02.png)

Thank You for your help Charlie Poole!

**Comment by wafnetcore** [comment]
Excellent Help Thanks Again!

**Comment by CharliePoole** [comment]
Glad that it helped. I'm closing this as a question, but if you have any follow-up, you can post it here and we will see it.
