### ISSUE TITLE
Crashes when NUnit3TestAdapter is present

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit-console#1046]
Nunit.COnsole 3.13
Adapter 4.1
NUnit 3.13.2
netcoreapp3.1

Repro :  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue912 

Command:  nunit3-console Issue912.dll

Result:
![image](https://user-images.githubusercontent.com/203432/144750932-bbee01ca-fc03-460d-af40-e1faec152c3f.png)

The adapter has embedded engine DLLs, but the same error happens if these are deleted from the output folder.

**Comment by CharliePoole** [comment]
@OsirisTerje It's not clear from the repo project how the console runner gets into your netcoreapp3.1 directory. How is it installed?

**Comment by OsirisTerje** [comment]
@CharliePoole It is globally installed, it is not in the same directory

**Comment by CharliePoole** [comment]
But you're typing `nunit3-console Issue912.dll` in that directory. So I was wondering if you used the chocolatey package, the msi, or what? AFAIR only chocolatey sets up an alias.

**Comment by OsirisTerje** [comment]
The MSI was used to install it

**Comment by CharliePoole** [comment]
OK... I'll install the same way and check it out.

**Comment by CharliePoole** [comment]
I first installed using chocolatey (because it's so much easier) and was able to run without error.

I next uninstalled the chocolatey package and installed the msi. I added the directory containing nunit-console to my path. Got the same error as you.

So, the error is in the msi packaging. I'll investigate further, but consider using the chocolatey install as a workaround. It has the advantages that (1) you don't need to mess with your path and (2) you can add and remove extensions independently.

BTW I like your idea of having a separate repo for bug repros. I think I'll do the same.

**Comment by CharliePoole** [comment]
@OsirisTerje You could also try deleting addins from your install, if you are not using them.

**Comment by CharliePoole** [comment]
Verified that the problem still exists in 3.15.

**Comment by CharliePoole** [comment]
Since this problem is limted to the MSI package, which we eliminated in 3.18.0, I'll close this.
