### ISSUE TITLE
Upload TestResults.xml as part of the build in Appveyor 

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit-console#1174]
From https://gitter.im/nunit/nunit?at=621d255c6b91242320103054 it was suggested that we should also upload the test results of the builds (as artifacts). 

@batzen also had the following comment
> Appveyor supports uploading test results. Have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/appveyor.yml

**Comment by CharliePoole** [comment]
Interesting... the reason given for needing it is the reverse of when we might want it ourselves. That is, we generally only need to see the result if there is a failure, in which case it's visible in the log. I assume that's why nobody ever bothered to upload them before. But @Archana-N wants to see the full output for a test run with no failures (since we only publish a release if there are no failures). We can do this of course, but it's an interesting difference in viewpoint. :-)

**Comment by rprouse** [comment]
This is an interesting one. I'm curious what in our test results they would look for to evaluate whether or not to use NUnit in their organization.

**Comment by CharliePoole** [comment]
I wonder as well. The most they would get is a list of passing tests... potentially a long list. As a "floating" coach / consultant, I ran into a lot of companies with similar rituals.

Ward Cunningham tells a story of one company with a medical application using FIT for it's tests. They wanted a report that listed the names of all the tests with PASSED or FAILED next to them. They got it and were happy. Somebody could easily create a ResultWriter extension to produce that sort of thing from our output, of course.

**Comment by OsirisTerje** [comment]
I've seen the same request from some organizations, they want the report as a kind of confirmation, or documentation really, to management that tests have been run and are passed.  Name of the tests are sort of the important thing, as far as I understood it.

**Comment by CharliePoole** [comment]
@nunit/engine-team Closed based on discussion. If anyone feels we should keep it, please let me know, but hopefully be prepared to implement it. :-)
