### ISSUE TITLE
When using XSL transform, the HTML output is getting some junk characters at the beginning of the file

### ISSUE THREAD

**Issue by varnk** [nunit/nunit-console#1204]
- The full command line being used
      **nunit3-console.exe "HubModuleTest.dll" --x86 --work=.\TestOutput --timeout=0 --trace=Off --**result:"ResultDetails.html;transform=html-ResultSummary.xslt" --result="TestResult.xml"****
- Method of installation (e.g. NuGet, zip, msi)
    **Nuget**
- Log files (Run the console with --trace=Debug to produce these)
**Log Files Attached**

- Version of the NUnit Engine/Console
**3.14.0**
- All versions of the NUnit Framework in use
**NUnit 3.13.3**
- Whether the behaviour is any different when the tests are run using the --inprocess flag
**Cannot run inprocess with --x86 option**

Problem:  
When running the console runner, the HTML output file that is produced has three junk characters at the beginning of the file (hex ef bb bf).  These characters are not in the transform XSLT file (also attached in the zip file).  They are not printable characters and can be seen when using a hex editor on the HTML file.   The characters are displayed when embedding the HTML in an e-mail.
[TestOutput.zip](https://github.com/nunit/nunit-console/files/9252512/TestOutput.zip)

**Comment by CharliePoole** [comment]
The sequence `ef bb bf` at the start of a file is the UTF-8 encoding of the Unicode Byte Order Mark. It isn't actually required for UTF-8, since it isn't a multi-byte encoding, but is permitted since some programs may use it to determine that the file is UTF-8. If any program is assuming the output is, for example, ascii, they would definitely be confused by it.

There's a question in my mind about whether we should change this behavior. It has been around for a long time and can't even be discovered except by resorting to a hex editor. I tried to see if the file would break any browser - it didn't. I could also view it in a variety of editors without problem. I also embedded the file in an email using two different clients without problem. Only by installing ghex was I able to see the problem. Would a change break anybody's existing usage? I'm guessing not but I hate to experiment on users.

Before  going further, can you apply the knowledge that this is a byte order mark to see if you can live with it in your own usage?

Charlie

**Comment by varnk** [comment]
I didn't really notice the encoding bytes when viewing in a browser or even in a text editor for that matter.  It became noticeable when I used Jenkins pipeline to embed the html output into an e-mail using content-type="text/html".  When I opened up the e-mail, I could see the encoding bytes in the e-mail content in addition to the formatted HTML. 
Here is the Jenkins pipeline script that I use to embed the results:
```
            emailext to: env.EMAIL_RECIPIENTS,
                subject: "${env.MODULE_ID} Test Results",
                body: '${FILE,path="TestOutput/ResultDetails.html"}', 
                mimeType: 'text/html' 

```
I'm not an expert on formatting e-mail content, so I don't know why the characters show up in the e-mail, but they do show up.

**Comment by CharliePoole** [comment]
I'm not an expert in this either, nor in Jenkins, but I think you would have to read the file yourself, possibly specifying the encoding, and then use the string in the body of your email. Perhaps someone else can supply code for that.

However, as a simpler alternative, why not just send a link to the result file, wherever it is on your site?

**Comment by varnk** [comment]
I could send a link to the results file, but my team prefers to have the report embedded in the e-mail.  

One thing that I did find out is that when I run another XSLT to HTML tool against my XML file, it embeds the UTF-16 encoding characters (ff fe) at the beginning of the produced HTML from the XSLT file.  However, if I force the XSLT to have a UTF-8 encoding in the Output element, then the tool omits the encoding info, but nunit-console still puts the UTF-8 characters at the beginning of the file.

`  <xsl:output omit-xml-declaration="yes" indent="yes" encoding="UTF-8" />`

As pointed out earlier, these encoding chars are not rendered by browsers or text editors, but for some reason Outlook is displaying them in the embedded e-mail content.  Perhaps there is something else I need to add to the e-mail content header or to the XSLT itself to eliminate this issue.  

At this point, I am not sure if this is an issue with nunit-console or if it is something deeper.

**Comment by CharliePoole** [comment]
@varnk 

See this: https://www.w3.org/International/questions/qa-utf8-bom.en.html

It seems clear that the general problem is considered to be one for the consumer to solve. My guess is that Outlook actually knows how to deal with a BOM but that it's not getting the chance because you are actually copying the entire file into the body of the email. You need to read the file to a string in some way, which recognizes and eliminates the BOM. If that's not available in a jenkinsfile, then you need to eliminate the BOM yourself. If you do it yourself, you should be aware that if you read the file as a string of bytes, the encoding will have three rather than two extra bytes at the start.

I'm closing this issue but you can ask still questions or comment here and I'll answer.
