### ISSUE TITLE
--output outputs empty file?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1283]
Here's my Nunit3 console command:

`nunit3-console.exe "%slnfile%" /config:Debug --skipnontestassemblies --out="%outputtext%"`

And although %outputtext% is created, but there is no content in it ( despite that I do see some content on the Console screen).  

Is `--output` command line parameter working?

**Comment by mikkelbu** [comment]
I've transferred this to the nunit-console repository. Which version of the console are you using @WindingWinter ? and can you create a small project that shows the problem.

**Comment by CharliePoole** [comment]
Not enough info here yet to accept this as an issue. Need version of console runner and package type from which it was installed, version of VS project loader extension, which would be required in order to run from a solution file, more explicit info about what you expected to see versus what you are actually seeing output.

**Comment by CharliePoole** [comment]
Closing for lack of info to reproduce the issue.
