### ISSUE TITLE
NUnit does not load AppContextSwitchOverrides from test assebly config files

### ISSUE THREAD

**Issue by vgriph** [nunit/nunit-console#1364]
When running tests, NUnit uses most settings from the test assembly config file. However the values in configuration/runtime/AppContextSwitchOverrides are not used. Instead the value of that setting from the nunit-agent.exe.config is used.

To reproduce, create a simple test project with the following app config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.Threading.UseNetCoreTimer=true" />
  </runtime>
</configuration>
```
And add a simple test case:
```cs
[Test]
public void ShallHaveUseNetCoreTimerSwitch()
{
    var found = AppContext.TryGetSwitch("Switch.System.Threading.UseNetCoreTimer", out var enabled);
    Assert.Multiple(() =>
    {
        Assert.That(found, Is.True, "The setting shall exist in the AppContext");
        Assert.That(enabled, Is.True, "The setting shall be enabled in the AppContext");
    });
}
```
I've tested with several different test runners and versions (NUnit-console, ReSharper, TestCentric) including NUnit Console 3.15.5 and all show the same behaviour.

**Comment by OsirisTerje** [comment]
@CharliePoole Is this a bug or by design?

**Comment by CharliePoole** [comment]
@OsirisTerje It's by design that the NUnit config is separate from the config associated with the executing program (app.config). The reasons are explained in this ancient text: https://charliepoole.org/technical/how-nunit-finds-config-files.html. :-)

The app.config files, which VS renames to 'someprogram.exe.config' is read and used by .NET __before launching the executable__ - that is, nunit-console.exe or nunit-agent.exe. NUnit itself, when loading a test, associates the test assembly with a specially named config (as described in the article) so that it may be read by the tests if necessary. 

Also underlying this is the idea that the config used with a test may need to be different from the config used when running the application under test in production.

However, while the overall design is intentional, I suspect there may be a bug related to agents. I have a memory of discussing such a problem but I can't find an issue for it. Of course, it may not be in the right project as often happens. It may also have been in TestCentric, which inherits a lot of features, as well as bugs, from NUnit. :-)

**Comment by vgriph** [comment]
I had a look at the code, and I  guess that if it is a bug, it is s bug within the .Net Framework app domain configuration handling, but it might just as well be by design that the AppContext switch overrides are not read by other than the default app domain.

I guess I'll have to work around the issue by either setting the switches programmatically by means of a setup fixture or an attribute, or changing the nunit-agent configuration file before executing the tests.
