### ISSUE TITLE
Allow one to set the Internal Trace location

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1388]
I use the command line parameter ` --trace=Verbose`, and I found that Internal Trace file will be generated at my current directory.

But is there a flexibility for me to specify where can I put my Internal Trace file? Because when I start from command line prompt, I can start anywhere, including from C drive.

**Comment by CharliePoole** [comment]
The console runner stores both log files and the TestResult.xml file in a "working directory." This defaults to your current directory but may be changed by using the --work option on the command-line.

As an historical note, NUnit V2 actually _changed_ the process current directory to be that of the test assembly. We stopped changing current directory in V3, because that's considered bad behavior for an application.
