### ISSUE TITLE
--inprocess bug(?): unable to read the App.config value

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#1390]
Here's a simple way to reproduce the issue. Make sure that your test assembly has `App.config`, and you define a key and a value with the name `MemoryReportDir`.

Then the below test will always pass, the `TestContext` will output whatever value that you define in App.config.

```
        [Test]
        public void AppConfig()
        {
            TestContext.WriteLine(ConfigurationManager.AppSettings.Get("MemoryReportDir"));
            Assert.IsNotNull(ConfigurationManager.AppSettings.Get("MemoryReportDir"));
        }
```

BUT, if you run the nunit console with `--inprocess` parameter, then `ConfigurationManager.AppSettings.Get("MemoryReportDir")` will be `null`. Is this a bug?

**Comment by stevenaw** [comment]
Can you please share the full command line you're using to invoke the runner?

I'm curious, have you tried specifying the config file to use on the command line via the `--configfile` argument? I don't see that arg documented on https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html

But I found this PR after searching the console runner repo for issues related to your question. https://github.com/nunit/nunit-console/pull/348/files

It seems to have existed since version 3.8. Please let us know if it works for you so we can update the documentation 😃

**Comment by WindingWinter** [comment]
@stevenaw, here's how I specify the command line:

```
"%NunitConsole%\nunit3-console.exe" "%slnFile%" /config:Debug --inprocess --configfile --labels=Before --skipnontestassemblies --result="%testresultxml%"  --timeout=600000 > "%testresulttxt%"
```

I'm using 3.16 for nunit console, and 3.13 for nunit framework. So I think that the `--configfile` flag doesn't work. You can try on your side.

**Comment by stevenaw** [comment]
Based on the linked PR you will need to pass in the path to your config file, similar to how you pass labels. For example:

```
--configfile=your.app.config
```

**Comment by WindingWinter** [comment]
@stevenaw , OK, now it works.

**Comment by stevenaw** [comment]
That's great! I'm glad it's working for you. Appreciate your help for testing it out and confirming 😃
I'll file a separate ticket against our documentation repo to make this feature more visible for others.
