### ISSUE TITLE
Package NUnit.Console 3.15.3 missing from nuget.org

### ISSUE THREAD

**Issue by jzabroski** [nunit/nunit-console#1402]
Hi,
I am seeing these errors in my dependabot logs for FluentMigrator.  
I definitely have a real/correct package version.  https://github.com/fluentmigrator/fluentmigrator/blame/main/test/FluentMigrator.Tests/FluentMigrator.Tests.csproj#L31
When I go to nuget.org, even there it says the package is just flat-out missing.  Why am I so confused? https://www.nuget.org/packages/NUnit.Console/3.15.3#readme-body-tab

As my blame history suggests, "NUnit 4 requires 3.15.x instead of 3.16.x (strange but true)".  The 3.15.4 release notes and 3.15.5 release notes dont really explain why 3.15.3 would be deprecated/removed from nuget.org.  What's also puzzling is I thought nuget.org had a no-delete permanent archival policy, and would simply warn if there was some vulnerability found.

![image](https://github.com/nunit/nunit-console/assets/447485/1941d4f2-f513-4bc9-9eb6-bfa28456cf87)

updater | dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.9.6+a4ecab324 for .NET
updater |   Determining projects to restore...
updater | /tmp/package-dependency-resolution_sNY66c/Project.csproj : error NU1102: Unable to find package NUnit.Console with version (= 3.15.3)
updater | /tmp/package-dependency-resolution_sNY66c/Project.csproj : error NU1102:   - Found 47 version(s) in NuGet Feed [ Nearest version: 3.15.4 ]
updater | /tmp/package-dependency-resolution_sNY66c/Project.csproj : error NU1102:   - Found 0 version(s) in fluentmigrator
updater | /tmp/package-dependency-resolution_sNY66c/Project.csproj : warning NU1903: Package 'Npgsql' 8.0.1 has a known high severity vulnerability, https://github.com/advisories/GHSA-x9vc-6hfv-hg8c
updater |   Failed to restore /tmp/package-dependency-resolution_sNY66c/Project.csproj (in 3.83 sec).

**Comment by OsirisTerje** [comment]
There never has been a 3.15.3.  You can see the release list here:  https://github.com/nunit/nunit-console/releases  .  I know we had some issues back at that time, but afaic remember, we didn't publish 3.15.3, but jumped directly from 3.15.2 to to 3.15.4. 
I've also checked the version list on nuget, and the only unlisted package there is 3.15.1, so I am pretty confident 3.15.3 didn't exist.
However, there was a 3.15.3-dev-build that existed on myget, and on myget (which is used for temporarily packages, dev builds, alpha versions and so on), they can and are being deleted, actually automatically.  I see 3.15.3-dev-build has been deleted there, ref. https://www.myget.org/feed/nunit/package/nuget/NUnit.Console

About the 3.16.X - these are a branch that we had to abandon, and we're slowly moving the fixes there into the 3.X branch which goes 3.15.X - 3.17.X and upwards.  

NUnit 4 doesn't have any requirement on the Console or Engine (which are versioned and sourced together), but the adapter has, which can be found here:  https://docs.nunit.org/articles/vs-test-adapter/Adapter-Engine-Compatibility.html
And since you have adapter 4.5 there, you should use Console/Engine 3.15.4.

**Comment by jzabroski** [comment]
OK, will close, thank you.

Still puzzled restore didn't fail with an invalid package version.
