### ISSUE TITLE
Console output is unclear about which console build is running

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1467]
We have three different builds of the console runner, all producing the executable `nunit3-console.exe`:

1. The "standard" console built with .NET Framework 4.6.2, which has full functionality.
2. The "netcore" runner built with .NET Core 6.0, with limited functionality.
3. A second "netcore" runner, with the same limited functionality, built against .NET Core 8.0.

Often, users don't actually remember which console they installed, resulting in a lot of confusion both for them and for the team when bugs are reported. For example, if the user says they are using .NET 6.0, that may mean they are using either the standard runner with a .NET6.0 agent or the .NET 6.0 runner or even the .NET 8.0 runner!

Ideally, we should not have three different programs with the same name. However, changing the executable name is a breaking change and will need to be postponed until the 4.0 release.

To mitigate the problem, the initial header in the console output should clearly state which of the three is being run. We might even consider a one-line notice like "Bugs should be reported against XXX."

It might also be useful to have a page somewhere, which describes the limitations of the .NET Core builds.

**Comment by OsirisTerje** [comment]
I believe we have a lack of documentation here.  There is next to nothing in the docs.nunit.org.  The wiki here is also lacking in information.  Also, I cant find any docs about the difference in functionality between the framework version and .net core version so we need to improve this too.

In order to figure out what you have, there are a few steps:

```cmd
where nunit.exe
```
This command tells me where the dotnet core version is located, which was installed as a dotnet tool:
![image](https://github.com/user-attachments/assets/a1393400-19c4-4fa7-a069-5d4431a7265b)

One can see that this tool is installed, and is located in the dotnet folder as expected for a dotnet tool.

If we now run 
```cmd
dotnet tool list -g
```
![image](https://github.com/user-attachments/assets/c86892ca-4857-4cce-a7cd-76336eb60b53)

We here see I have it installed as version 3.18.1

Now, I'll go look for any other installations using:

```cmd
where nunit3-console.exe
```
And, it finds 2 installations, one obviously done using `chocolatey`:
![image](https://github.com/user-attachments/assets/d3146a94-0fa0-4ad2-abbc-a5a8f0dc0e6f)

Since these are .net framework based tools, I can use a powershell command to figure out what they are:

````cmd
powershell -NoProfile -command "[System.Reflection.AssemblyName]::GetAssemblyName('C:\path\to\yourapp.exe').Version.ToString()"
```
which gives the following versions:
![image](https://github.com/user-attachments/assets/9eff183a-e151-42a5-bbb0-50fe80826bd9)

So you can use the command `nunit` which will start the net core dotnet tool version.  If you use the command `nunit3-console`, it will start the first one found in the `where`` command list.

**Comment by WindingWinter** [comment]
@CharliePoole , is it even possible to install a different nunit console runner other than the standard ( .net framework) one? Because when I get my nunit console from nuget, I can only get one version-- the .net framework version.

**Comment by CharliePoole** [comment]
@WindingWinter Well it depends on  which package you install. NUnit.ConsoleRunner is what I'm referring to as the "standard" runner, NUnit.ConsoleRunner.NetCore is the netcore runner.

**Comment by CharliePoole** [comment]
@WindingWinter Just looking back at this exchange and wanting to clear up a point. You may already know this, but for the benefit of anyone who doesn't, here goes...

The "standard" runner, which runs under .NET Framework, is still able to run tests under .NET Core using agents. In version 3.18.1, it comes with agents for .NET Framework 4.6.2, .NET Core 3.1, .NET 6.0, .NET 7.0 and .NET 8.0. If you use all defaults on the command-line, the runner selects the best agent for each test assembly.

OTOH the .NET Core runner runs one assembly at a time, in process, under .NET 6.0 or under a higher-level framework if you have set up your config to do that.
