### ISSUE TITLE
Assembly resolution may differ from command line supplied assemblies

### ISSUE THREAD

**Issue by tom-dudley** [nunit/nunit-console#166]
First off I'm not entirely sure if this a bug, perhaps some clarification would be useful.

- I have an assembly `Foo` sitting in `C:\x\x\Foo\bin` and another assembly `FooLibs` sitting in `C:\x\x\FooLibs\bin`.
- When I come to compile `Foo`, since I have CopyLocal turned on `FooLibs` gets copied into `C:\x\x\Foo\bin`
- I then issue `nunit3-console C:\x\x\Foo\bin\Foo.dll C:\x\x\FooLibs\bin\FooLibs.dll`

All of that is fine apart from the fact that `FooLibs.dll` is using `CurrentContext.TestDirectory` to find a path relative to `C:\x\x\FooLibs\bin`. The issue I am having is that it's looking for it relative to `C:\x\x\Foo\bin`.

Now my understanding of how the runner starts is that it arbitrarily chooses a directory to start up in. I think I read somewhere that this is the case, either here or on Stack Overflow. So what I believe is happening is that NUnit is 'started' in `C:\x\x\Foo\bin` , then attempts to find `FooLibs`, and loads the copied `C:\x\x\Foo\bin\FooLibs.dll`.

That being said, looking at the `LoadPackage `method in `DirectTestRunner` (which I think is the runner being called), it seems to be acting on the full path, which makes me think it should be working fine.

Could anyone provide clarification on this or what might be causing the issue?

**Comment by CharliePoole** [comment]
NUnit does not "arbitrarily choose" a directory to start in, you do! 😄 

NUnit never changes the current directory, so whatever directory you are in when you type the command - or when a script issues it - remains the current directory when NUnit is started. 

`TestContext.CurrentContext.TestDirectory` gives you the directory from which NUnit loaded the test assembly, which in your case is `C:\x\x\Foo\bin`. So, the question is why is NUnit using that directory?

I'm guessing that one of your other assemblies references FooLibs.dll, which is why you have copied it to the bin directory. My guess is that the reference causes the copy in the bin directory to be loaded initially. Then, when NUnit tries to load the assembly, .NET discovers it is already loaded and uses that loaded copy. This is unavoidable given how .NET and NUnit work together.

It's generally a bad practice to have one test assembly referring to another test assembly, for exactly this reason. Can you eliminate any reference? Barring that, if there are files in the same directory as FooLibs.dll that you want to have available, copy them to the bin directory along with the dll.

**Comment by CharliePoole** [comment]
PS: If I guessed wrong about the reference, feel free to continue posting here and we'll discuss further.

**Comment by tom-dudley** [comment]
Thanks Charlie, I didn't stop to consider properly why the one test library was bringing in the other. It's probably some supporting classes which I can pull out into a separate assembly.

No idea where I got the crazy startup behaviour idea from!
