### ISSUE TITLE
3.6.1 is missing the .zip file.

### ISSUE THREAD

**Issue by Clancey** [nunit/nunit-console#189]
The latest release is missing the .zip file for the Unit.Console runner. (Unit.Console-3.6.1.zip)

https://github.com/nunit/nunit-console/releases/tag/3.6.1

**Comment by rprouse** [comment]
There must be a build step missing in our docs, I didn't produce a ZIP file this time. We are still documenting the release process now that we split the framework and console, so I will need to look into it.

**Comment by CharliePoole** [comment]
@rprouse I believe the zip is produced in the nunit-distribution project and has to be copied over. I wonder if we may have made a mistake in separating that project from the nunit-console repo.

**Comment by rprouse** [comment]
@CharliePoole I built the MSI using the nunit-distribution project, but a ZIP didn't get built. I think I just ran the build step `PackageMsi` rather than `PackageAll` in that project. I haven't touched that directory, so I ran it now and it produced the Zip, so I will upload it.

As for separating out the packaging, it is a bit of a pain because it depends on NuGet packages being live, but it is pulling packages from several repositories, so it is conceptually correct IMHO 😄

**Comment by rprouse** [comment]
I have updated the release with the ZIP file.

**Comment by CharliePoole** [comment]
@rprouse I didn't realize it pulled from other repos - thought it just downloaded the live packages. In that case, separate is logical.

**Comment by rprouse** [comment]
Misspoke, it does pull live packages. Just referring to the other repos as the source of the live package releases.
