### ISSUE TITLE
Better logging or error handling in SettingsStore.SaveSettings

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit-console#194]
Several people in the nunit-gui project have reported problems with corrupt Nunit30Settings.xml files (see for instance nunit/nunit-gui#130 or nunit/nunit-gui#162). 

The code in `SettingsStore.SaveSettings` however makes it difficult to pinpoint these problems as the code catches all exceptions (it also forgets to dispose the XmlTextWriter, but this is problably not relevant in this issue).
https://github.com/nunit/nunit-console/blob/8cb7226c0ad683fe5eb7a4eee8989aff08dc4ccb/src/NUnitEngine/nunit.engine/Internal/SettingsStore.cs

I propose that the method is changed such that it either:
* rethrows the exception after setting `_writeable = false` and then captures it further out the callstack where it can be logged (as far as I can tell the exception will be captured in `ServiceManager.StopServices`)
* logs the exception directly in `SettingsStore.SaveSettings`

**Comment by CharliePoole** [comment]
I agree the code looks strange, but there are some valid occasions where the settings cannot be saved because there is no valid location at which to write them. However, this fact should be logged as you suggest.

**Comment by CharliePoole** [comment]
I just noticed that the original description refers to the gui project. Everyone working on the gui project should be aware that we don't always use the production engine. At this issue was reported, we were not using it so that could lead to some confusion when trying to reproduce errors. 

Recently, I updated the gui to use the latest production engine, so this is a good time to be working on this issue. However, it's almost certain that we will go back to using a special engine after the 0.4 release.
