### ISSUE TITLE
Remove output of test from the xml report

### ISSUE THREAD

**Issue by psandhu79** [nunit/nunit-console#197]
We run tests which produce a lot of output , we do not want these to appear in the xml result file only in the file specified using the following comamnd line switch --output

**Comment by CharliePoole** [comment]
The fundamental output from any NUnit test run is the xml. It has to contain __all__ the information because it's the source of any __other__ output you may request. A command-line option that changed the fundamental output could potentially break other things.

That said, you're specific request isn't terrible. We could have an option that said "Don't record any text output in the xml result. This would basically eliminate the `<output>` element. But what if we then get other requests to change the output format. We could end up supporting a combinatorial explosion of output formats.

An alternative suggestion is to use a transform to modify what is __saved__ from the output. This option is available using `--result:TestResult.xml;transform=MyTransform.xslt`, where MyTransform simply removes all the `<output>` elements.

Of course, it's possible for us to define a new internal format, e.g. `--result:TestResult.xml;format=NoOutput`, but I would want to see a general demand for the format before adding it to our backlog. 

For now, I suggest using a transform.

**Comment by CharliePoole** [comment]
BTW, another reason not to change the fundamental format is that you can save the result more than once, using different formats based on the nunit3 output.
