### ISSUE TITLE
Are NUnit v3.6.X console test results xunit-compatible?

### ISSUE THREAD

**Issue by joel74** [nunit/nunit-console#204]
Hi,
I'm upgrading from v2.6.3 to v3.6.1. We use Thoughtworks Go to parse and display our NUnit test results. Go complains that the test output from v3.6.1 isn't xunit-compatible. ("Ignoring file TestResult.xml - it is not a recognised test file.") If I format the test output as NUnit2, it is accepted. Is this expected? Does NUnit3 output not conform to the xunit schema?

Thanks,
Joel

**Comment by CharliePoole** [comment]
Not sure what you mean by xunit-compatible. There is no genrally accepted result format supported by all xunit-style test frameworks. If there were, we would rush to support it as an option!

NUnit 3 result output is not the same as V2. NUnit 3 has much more information to display in its results than can be represented in the V2 format. That's why we support V2-format output, which we create containing information as close as possible to what V2 would give for the same tests. Obviously, new things such as multiple assertion results and warnings cannot be represented without expanding the format.

It's up to the authors of products like the one you are using to decide what input formats they want to support.
