### ISSUE TITLE
There is no tag for 3.7.0 release

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit-console#230]
nunit-framework was released, but nunit-console wasn't...

**Comment by CharliePoole** [comment]
The framework and console are independent programs each having its own release schedule. Since they started out at the same version with 3.0, the numbers are still close but expect them to diverge in the future especially as the teams that work on them change.

The fact that was one is in a separate repo indicates their separateness.

**Comment by ArsenShnurkov** [comment]
but anyway, nunit-console should be a bit updated, for example it references older version of framework

/usr/lib64/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'nunit.framework, Version=3.6.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL' not resolved

**Comment by rprouse** [comment]
@ArsenShnurkov the NUnit reference is to the framework which will be updated in time, but the 3.6.0 version should still work and build. You are building on Mono, so I expect that you have not restored NuGet packages? I would recommend building using the Cake build at that command line with a command like `./build -Target=Test`

Also be aware that we have had issues with Mono recently and that running the tests crashed mono on versions newer that 4.2.8 and older than 5.0.1 (those numbers are off the top of my head and may be slightly off).

**Comment by CharliePoole** [comment]
@ArsenShnurkov The reference to the framework is not from the engine or console, but from the tests. Like any tests, they have to reference some version of the framework, but there is no reason to update them. Allowing users to run tests using older framework versions has been a feature of NUnit for many years and it applies to our own tests as well.

**Comment by ArsenShnurkov** [comment]
@rprouse I am trying to update packages for portage package manager. I don't want to use Cake, because it is additional dependency, which is not packaged for gentoo yet.

**Comment by rprouse** [comment]
@ArsenShnurkov may I ask why you are attempting to build without pulling packages from NuGet and instead trying to use installed packages for your dist? Pretty much every programming language has package management systems and most people use them no matter which distro they use. I wouldn't even attempt to get Node programs running without NPM.

You also don't need to install Cake on Gentoo, you just need to run our build script and it will install a local copy of Cake in the tools folder of the source. You will have a much better build experience if you use our build. We cannot maintain builds for every potential build environment.

**Comment by CharliePoole** [comment]
To put us all on the same page...

Gentoo packages are generally source, although binary packages are now possible.

I believe most binary packages come from upstream - which would be us in this case.

I __think__ that @ArsenShnurkov us actually trying to create the package for the distro.

**Comment by ArsenShnurkov** [comment]
It's illogical to use gentoo and foreign binary packages together. In this case it is better to use Ubuntu.
Binary packages from upstream are also compiled from sources, but this is done by binary gentoo-based distributions, like Sabayon or Calculate Linux. You are not the binary upstream in any case.
Trisquel have policy of not using external blobs. Why not to have the same for me?

**Comment by CharliePoole** [comment]
My point was that for there to be a binary distribution of NUnit, NUnit would have to produce it. If we did, however, most distros would not accept it - users would have to install it directly. All the distros I work with require source to be built so that they know what is going into the distro.

"Why not to have the same for me?"
I don't understand. Your policy is whatever you want it to be. It's not in our control at all.

What you could tell us, which may help, is exactly what you would like to see us do in order to make it easier to maintain the package. So far, what I understand is that you would like us to actually support building the console and engine under mono 4.5 profile. Anything else?
