### ISSUE TITLE
Plan for 3.7 Release

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#231]
This project is overdue for a release and I think the fix from #223 is serious enough to warrant getting an update out soon. I have set the milestone to Sunday to give us rough timings. @nunit/core-team and @nunit/engine-team, does this sound reasonable?

If there are issues or related PRs that we should consider including in the release, please assign them to the 3.7 milestone so we can track them.

**Comment by ArsenShnurkov** [comment]
I have some questions (don't know should i create a separate issue for asking them), they are:
1) why <a href="https://github.com/nunit/nunit-console/blob/e39fc7fed5d122aff26eb7b22b565c35b34a6e2c/src/NUnitEngine/nunit.engine/XmlHelper.cs#L32">this line<a> is not under conditional directive ? I am trying to build this project for .NET framework 4.5, and I don't have v2.0 installed. During compilation it five me error about Attribute duplication.
2) <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Extensibility/ExtensionNode.cs#L134">this line</a> give an error
Error CS0618: Warning as Error: `System.AppDomain.CreateInstanceFromAndUnwrap(string, string, bool, System.Reflection.BindingFlags, System.Reflection.Binder, object[], System.Globalization.CultureInfo, object[], System.Security.Policy.Evidence)' is obsolete: `Use an overload that does not take an Evidence parameter' (CS0618) (nunit.engine)
in <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Drivers/NUnit3FrameworkDriver.cs#L169">some other place</a> it was placed under NET_4_0, but not here.
3) Some more similar errors <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Services/DomainManager.cs#L67-L75">here</a>

**Comment by rprouse** [comment]
@ArsenShnurkov could you please copy your question into a new issue? This issue is for planning the release. Happy to help you  with your mono questions, but I don't want to pollute this issue.

**Comment by CharliePoole** [comment]
How do you want to handle the chocolatey issue?

**Comment by rprouse** [comment]
I will admit that I am less bullish on Chocolatey than I used to be, but the PR looks nearly done, so it would be good to include it in our release and start updating Chocolatey with it. It will be a few days until I can get to the release since I want to do the framework hotfix first, so we have time for this. I will review the outstanding PR soon.

**Comment by CharliePoole** [comment]
I created a branch (issue-207) and pulled in the changes from @Roemer 's branch. Creating the package and installing it locally, it works but I see unexpected failures in the tests. It may be because I'm running NUnit's own tests and there is some strange interaction going on, so I'll have to retry it tomorrow.

In looking at this more closely, however, I see that it may be possible to avoid copying all the extensions into a single package and to use references as we do for the nuget package. I would have to consult with the chocolatey guys to be sure.

Do you feel this has to go out at the same time as the 3.7 release? It seems like we could put out a chocolatey package using the 3.7 binaries at any point after the release.

I'd like to hear why you are not feeling as positive about chocolatey as before. I was thinking of making it the sole binary distribution for the gui.

**Comment by ChrisMaddock** [comment]
@rprouse - I'm happy with this repo.

Regarding https://github.com/nunit/nunit-distribution/issues/17 - I don't think I'll have time to sort this over the next couple of days, unless you do, could you manually remove the two extraneous files for this build? It only affects the zip, not the msi.

**Comment by agray** [comment]
My project is now consuming NUnit 3.7.1 NuGet Package.  What version of the NUnit Console MSI should I install to be compatible with this?  My console log is hanging:

    C:\Jenkins\workspace\FullCircle\Saucery\Saucery3NUnit>"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" Saucery\NUnit\Version3\UnitTests\bin\Release\UnitTests.dll --result:junit-unittests-testsuite.xml;transform=nunit3-junit.xslt --trace=Verbose  
    NUnit Console Runner 3.6.1 
    Copyright (C) 2017 Charlie Poole

    Runtime Environment
       OS Version: Microsoft Windows NT 10.0.14393.0
       CLR Version: 4.0.30319.42000

    Test Files
        Saucery\NUnit\Version3\UnitTests\bin\Release\UnitTests.dll

Is there a 3.7.1 version of the NUnit Console coming soon?

**Comment by agray** [comment]
Attaching my verbose logs:

[Saucery3NUnit.zip](https://github.com/nunit/nunit-console/files/1057190/Saucery3NUnit.zip)

**Comment by CharliePoole** [comment]
There is no intended correlation between  the version numbers of the framework, engine and console. Right now, for example, the NUnit team runs all it's NUnit 3.7.1 and beyond tests using the 3.6.1 console.

Looking at your logs, it seems that the hang takes place when you reach your FlowControlTest. If you examine this and still feel it may be an NUnit problem, please create a new issue rather than piggybacking on this one.

**Comment by jnm2** [comment]
I am running into the SocketException bug fixed by #223 over and over when I run the build script for the NUnit framework. I haven't gotten a clean run in the last four tries. How soon do you think we can get at least that fix out?

**Comment by jnm2** [comment]
Hmm, it's to the point where I can't test net20 - net45 using build.cake at all.

**Comment by CharliePoole** [comment]
@jnm2 We should join forces - I can __only__ test net20 - net45. :smiley_cat:

**Comment by rprouse** [comment]
@nunit/engine-team I am planning on doing the 3.7 release on Thursday. If anyone sees an issue with that, please speak up 😄
