### ISSUE TITLE
Agent TestEngine contains duplicate services

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#248]
I'm not familiar with this section of code, but I presume this is unintentional.

In the nunit-agent Main() method, it creates an engine, and then adds some services, roughly:

```
            TestEngine engine = new TestEngine();
            engine.Services.Add(new SettingsService(false));
            engine.Services.Add(new ExtensionService());
            engine.Services.Add(new ProjectService());
            engine.Services.Add(new DomainManager());
            engine.Services.Add(new InProcessTestRunnerFactory());
            engine.Services.Add(new DriverService());
```

It then calls `engine.Initialize()`, which adds the following services:

```
            Services.Add(new SettingsService(true));
            Services.Add(new DomainManager());
            Services.Add(new ExtensionService());
            Services.Add(new DriverService());
            Services.Add(new RecentFilesService());
            Services.Add(new ProjectService());
            Services.Add(new RuntimeFrameworkService());
            Services.Add(new DefaultTestRunnerFactory());
            Services.Add(new TestAgency());
            Services.Add(new ResultService());
            Services.Add(new TestFilterService());
```

A number of services are duplicated between the two lists, which I assume shouldn't be the case?

**Comment by jnm2** [comment]
This is one of the problems with service location... *ducks*

**Comment by CharliePoole** [comment]
@ChrisMaddock It took me a second to figure out what `nunit-aged` was. 😄 

The agent is part of the engine. As such, it's the only program of ours - other than tests - that actually constructs an engine and initializes it directly with the services it wants, rather than using automatic initialization. So it should not be calling `engine.Initialize()` or `engine.Initialize()` should recognize that it has already __been__ initialized and not do anything.

Seems like this has been in there for a long time. It probably works because the services added initially are found first and the later additions are never used. I'll do a quick PR.

**Comment by ChrisMaddock** [comment]
> @ChrisMaddock It took me a second to figure out what nunit-aged was. 😄

Haha - whoops! Thank you.

**Comment by CharliePoole** [comment]
Well, it's a fine mess you got me into @ChrisMaddock !

Turns out, first of all, that many of our tests break when some of those services are not present. So, I fix that and discover that without a TestAgency service, the agent can't communicate using TCP any more. IOW, just as users sometimes do to us, we have become dependent on our own bug!

I'll fool with this a bit more, but it may have to go on the back burner.

**Comment by ChrisMaddock** [comment]
Oh dear - and I thought this would be a simple fix! 😄

**Comment by CharliePoole** [comment]
Nope, but a good catch! I think I have a fix now... PR shortly.
