### ISSUE TITLE
Console crashes when specifying both format and transform for result

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#252]
See below:

```
nunit3-console Tests.exe --result:results.xml;format=nunit2;transform=a.xslt

Unhandled Exception: System.ArgumentException: Conflicting format options: results.xml;format=nunit2;transform=a.xslt
   at NUnit.Common.OutputSpecification..ctor(String spec)
   at NUnit.Common.CommandLineOptions.<ConfigureOptions>b__124_13(String v)
   at NUnit.Options.Option.Invoke(OptionContext c)
   at NUnit.Options.OptionSet.Parse(String argument, OptionContext c)
   at NUnit.Options.OptionSet.Parse(IEnumerable`1 arguments)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

It appears transforms must only be used with the default format - but we should catch this exception and print a nice error message, like we do with invalid arguments. (It would also be helpful to document this more explicitly.)

**Comment by CharliePoole** [comment]
I agree with the goal of a nice message. 

The `transform` sub-option is only allowed with the `user` format. The default format is `nunit3` unless you specify a transform, in which case it is `user`.

Unfortunately, this is not a simple fix in the command-line options parsing. The console runner has no idea what format options are supported because extensions are possible, so only the engine can issue a message and the only way it has to do it is through some kind of exception. I think we need to find a way to distinguish between exceptions that are require a full stack trace and those that simply terminate with a message. We currently use NUnitEngineException for the full dump, so maybe we should define another one, such that the runner will know to simply display the explanatory message. That would be an additive change to the API. The alternative of adding a property to NUnitEngineException is a kind of change that would break compatibility.

**Comment by ChrisMaddock** [comment]
Initially, I was just planning this to be catching ArgumentExceptions thrown by the OutputSpecification ctor - which are thrown for invalid states such as format/transform being specified incorrectly (e.g. together/multiple times.)

Validating the formats parsed in is a bigger issue, yes. I'd say that's a separate issue though?

**Comment by CharliePoole** [comment]
Fair enough - I was getting ahead of you. :-) The whole question of how the runner supports extensions without being extendible itself is a problem. We actually "know" about some extensions, like teamcity, but I don't think we really should from an O-O standpoint.

But OutputSpecification, as you point out, only knows about the __fact__ that we have formats. Only nunit3 and user get a special treatment and they are built-in.
