### ISSUE TITLE
nunit3-console --testlist:FILE not working

### ISSUE THREAD

**Issue by tomaszchm** [nunit/nunit-console#265]
I have a list of tests in the tests.txt file. Each test is in a separate line:
```
file1.Tests.dll
file2.Tests.dll
file3.Tests.dll
```

1) When I run nunit3-console --testlist:tests.txt I get the following error:
```
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Error: no inputs specified
```
2) If I run "nunit3-console dummyfile --testlist:tests.txt" it lists the tests from the file, which means it is able to read the file:
```
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.15063.0
  CLR Version: 4.0.30319.42000

Test Files
    dummyfile

Test Filters
    Test: file1.Tests.dll
    Test: file2.Tests.dll
    Test: file3.Tests.dll


Errors, Failures and Warnings

1) Invalid : C:\dev\phq\sources\imageserver\tools\nunit-console\dummyfile
File not found: C:\dev\phq\sources\imageserver\tools\nunit-console\dummyfile
```
It looks like nunit3-console always require the _[inputfiles]_ parameter even if I specify _--testlist_ option, which in this case should be the input.
NUNIT3-CONSOLE **[inputfiles]** [options]

The only way I found to run the tests is to list all of them as _inputfiles_ parameter.
```
nunit3-console file1.Tests.dll file2.Tests.dll file3.Tests.dll
```

**Comment by ChrisMaddock** [comment]
I'm afraid you've misunderstood `--testlist`.

--testlist takes a file which contains a list of named tests, e.g. `MyNamespace.MyClass.TestA`. These are tests which are expected to be found within the files you specify.

If you definitely want to list you files in a separate file, rather than directly on the command line, then the `@FILE` option should be able to do that. See https://github.com/nunit/docs/wiki/Console-Command-Line
