### ISSUE TITLE
Capture Console.Write(Line) output in test result

### ISSUE THREAD

**Issue by bladeoflight16** [nunit/nunit-console#272]
It appears that the NUnit report format allows for the inclusion of [console output](https://github.com/nunit/docs/wiki/Test-Result-XML-Format#output) in its results.

Please add the option of *capturing* console output in this field in addition to (or instead of) printing it on the screen. The Visual Studio adapters already capture this output, and I believe the NUnit GUI does as well. So having this would make for a more consistent experience.

**Comment by CharliePoole** [comment]
Not sure what you are asking for. Console output is already attached to the test result.

**Comment by bladeoflight16** [comment]
Hm. My apologies. I'm somewhat stuck with a lot of old technology, and I'm just now exploring switching to this runner. (I've been using the old Gallio runner.) It appears that a combination of factors was contributing to my not seeing it in my test report.

 1. It doesn't show up if I specify the result format to be NUnit2.
 1. It doesn't show up if the test project uses a 2.x version of NUnit.

Is capturing console output completely unsupported by NUnit2? This is rather unfortunate if so, as I'm having a ton of trouble finding any viewers or decent converters (to graphical formats like HTML) for the NUnit 3 format.

**Comment by CharliePoole** [comment]
Associating  the output with each test result in the XML was a new feature in NUnit 3. NUnit V2 was able to capture output only for the purpose of displaying it in a panel of the GUI. 

For that reason, getting the text output to be associated with a test requires use of both the NUnit 3 framework and the NUnit 3 output format - the V2 format simply doesn't define any elements to hold the text.

**Comment by rprouse** [comment]
@bladeoflight16 to convert the NUnit 3 test results to an HTML report, try ReportUnit, http://reportunit.relevantcodes.com/

**Comment by LirazShay** [comment]
@rprouse 
ReportUnit does not support test output.
In the report that is generated by ReportUnit the output is not included in the html.
I'm using NUnit3 with SpecFlow, and till now I didn't find a good tool to convert the nunit3 result xml into html.
Because SpecFlow report only support nunit2 format so it does not show the categories but it show the output per test (the output is very important in SpecFlow tests)
And ReportUnit for nunit3 does not show the output, but has really nice design.
@CharliePoole in which tool do you use to parse the nunit result into html?
Maybe you have a suggestion?

**Comment by ChrisMaddock** [comment]
I don't believe there's an issue to be solved here. Happy to reopen if I've missed something!
