### ISSUE TITLE
NUnit Console Runner 3.7.0 reports that format nunit2 is unknown

### ISSUE THREAD

**Issue by riverhead013** [nunit/nunit-console#294]
Hello, I'm trying to set up nunit 3.7.0 using Bamboo CI.
Currently I'm getting next error:
`build	27-Sep-2017 13:13:43	Unknown result format: nunit2`

As a solution I've tried to put nunit-v2-result-writer.dll into tools folder but it didn't help.
Any suggestions?
![nunit](https://user-images.githubusercontent.com/11230919/30909015-4c53f9ec-a388-11e7-96e6-5f4f62d92b10.png)

**Comment by ChrisMaddock** [comment]
The path in your .addins file need to point to the location of nunit-v2-result-writer.dll. That will load the extension.

How are you getting the console runner onto your server? It looks like you've installed nunit.consolerunner from NuGet, and then manually copied in nunit-v2-result-writer.dll. If you install both NUnit.ConsoleRunner and NUnit.Extension.NUnitV2ResultWriter directly from NuGet, it should 'just work'. I'd recommend doing that, instead of editing your .addins file - unless you have a good reason not the use the default functionality.

Further details here: https://github.com/nunit/docs/wiki/Engine-Addins-Spec#locating-addins
