### ISSUE TITLE
Run NUnit tests on linux/debian

### ISSUE THREAD

**Issue by dialex** [nunit/nunit-console#303]
[Following your doc](https://github.com/nunit/docs/wiki/Console-Runner) it seems it is possible to execute `nunit3-console.exe` on linux to run the tests. However I got this error

```
$ ./nunit3-console.exe
-bash: ./nunit3-console.exe: cannot execute binary file
```

I gave it `+x` chmod permissions, but I got the same result. What am I doing wrong?

**Comment by CharliePoole** [comment]
For better or worse, the doc page only demonstrates running on Windows. Maybe we need to add a section toe Linux.

Some Linux distro are set up to run .exe files under mono without being told but others require you to use the mono command.

**Comment by ak200275** [comment]
I am very keen on knowing the present status and if anyone can help. I have created .NET Core 2.2 project using nunit framework I have written some testcodes. I have published the codes in visual studio 2017 which is self contained  for Linux 64 based. now I want to execute the tests in ubuntu container. I can copy this publish folder in Ubuntu and now what command should I give in order to run these tests. When I do not use nunit framework and write test codes in console application I am able to execute the tests. but not with nunit. please suggest with example I am novice on linux
--Thanks
Anuj

**Comment by ChrisMaddock** [comment]
Hi Anuj,

Take a look at the below page. Dotnet test is your best option for this situation currently:

https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard
