### ISSUE TITLE
Copying console runner exe to output directory

### ISSUE THREAD

**Issue by elektromodulator** [nunit/nunit-console#311]
The NuGet package lacks an MsBuild target file, so nothing happens with the package contents during build.
It would be handy, if the package would configure the project file, so the console runner exe is copied to the build output directory of the project.
Now I have to manually edit my project file to copy everything, every time I update the NuGet package to a new version.

**Comment by rprouse** [comment]
Why do you need to copy the runner into the build directory, just so that it is easier to find and type? Most users just run it from the tools directory from the packages folder in the solution root. Copying the runner would also mean that we would have to copy all installed NuGet extensions which would be a large rework.

Sorry, but we are unlikely to make this change without a fairly strong argument 😉

**Comment by CharliePoole** [comment]
@rprouse Not only would you have to copy all the extensions, but you would have to either (1) copy them so that their relative path from the original install was unchanged or (2) generate an entirely new `.addins` file, with contents dependent on which extensions are actually installed!

**Comment by bladeoflight16** [comment]
If you want an MSBuild task, there's no need to copy the executable to the output directory. You just need an MSBuild file that's referenced from the project.

The file can either contain set a property containing the NUnit console location, or it can contain a task to execute the tests. That isn't difficult, since the executable will always be in the known path of the packages directory. You'll still need to update *that* file when you upgrade, but then you only need to update the location in *one* file and you're done.

Alternatively, you could make your own NuGet package containing such a file and arrange it so that NuGet will update your project to reference the MSBuild file. The downside would be that you need to create a new version every time the NUnit console updates and update all your projects that reference it.

This request is what we call an XY problem.

**Comment by elektromodulator** [comment]
Sorry for not responding sooner, I got distracted with other projects, and completely forgot this issue.

I see that such request would really complicate things with addins, and since you are right that it's easy to work around this with build scripts (which I is what I did), I'll close this issue.
