### ISSUE TITLE
Should legacyCorruptedStateExceptionsPolicy enabled=true in nunit3-console.exe.config?

### ISSUE THREAD

**Issue by WindingWinter** [nunit/nunit-console#336]
I would argue that in the nunit3-console.exe.config,  the  legacyCorruptedStateExceptionsPolicy should be enabled by default.

The reason is that nunit console must cater to the widest range of audience possible, and it shouldn't present any surprises to them, or make their debugging lives difficult in the case of any scenario. In my case, a faulty third party native component throws an non-deterministic AccessViolationException after a few hours of running and thus causes the nunit runner to crash randomly ( similar to the case here (https://github.com/nunit/dotnet-test-nunit/issues/115) ).

If the Nunit just crashes like that because of AccessViolationException, I won't know whether the problem lies with the Nunit runner or my code ( or the code underlying mine). Worst of all, it will take me a long time to figure out what's the problem, as the problem doesn't always appear and even if it does, it only appears after quite a long time in running!

Furthermore, in nunit3-console 3.6.1, legacyUnhandledExceptionPolicy is already enabled by default, I don't see why legacyCorruptedStateExceptionsPolicy isn't.

**Comment by CharliePoole** [comment]
I'm not taking this issue on, but I wanted to point out that it's insufficient to set policy for the console runner, since that would only apply in the case where tests are run in process, which is not the default and AFAIK not done very often.

For widest application, any changes will need to be applied to the nunit-agent configs as well.

The situation was similar in NUnit V2 but in that case tests were run in process by default.

**Comment by nsoonhui** [comment]
Hi @CharliePoole , any reason why you don't want to set the policy on console runner ( or nunit-agent)?

**Comment by CharliePoole** [comment]
I haven't researched that policy setting in detail, so I neither want nor don't want to set it! I've heard it said that "Everyone has a right to an opinion" but I never believed that. 😉 

Closed the issue in error... so reopening... (that happens a lot - GitHub needs some UX folks!)

**Comment by rprouse** [comment]
I am not against enabling this, but would prefer to research any possible consequences before deciding. As @CharliePoole stated, it will need to be applied to the agents too.

**Comment by jnm2** [comment]
Since NUnit Framework has `[assembly: AllowPartiallyTrustedCallers]`, it can't handle process corrupted state exceptions (see https://github.com/nunit/nunit/issues/3295#issuecomment-507503500) unless we add this to the console and agent .config files.

One consequence of this is that @endrih's https://github.com/nunit/nunit/pull/2512 has never had any effect when using the console runner.

Another consequence is the intermittent NUnit console hang now that .NET Framework 4.7 and 4.8 have a race condition which causes stack trace formatting to throw AccessViolationException. (See all of https://github.com/nunit/nunit/issues/3295.)
