### ISSUE TITLE
TestEngine: 34 failed tests in NUnitAdapter - none via build

### ISSUE THREAD

**Issue by alski** [nunit/nunit-console#347]
![image](https://user-images.githubusercontent.com/991624/34889122-cecc765c-f7c4-11e7-8a15-13cdc47def5d.png)

When I run the tests via NUnitAdapter (v3) I get 34 failures, but when running via build all pass. It appears to be due to tests being unable to find the mock assemblies that the tests expect to run against, possibly due to the incorrect working directory. Still checking, just wanted to raise this for now.

`<test-suite type="Assembly" id="0-1" name="mock-assembly.dll" fullname="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\mock-assembly.dll" testcasecount="0" runstate="NotRunnable"><properties><property name="_SKIPREASON" value="File not found: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\mock-assembly.dll" /></properties></test-suite>`

**Comment by alski** [comment]
Ok, looks like this has been remedied in #if NETCOREAPP1_1 so just needs to cover these cases too. Pull Request coming shortly.

**Comment by alski** [comment]
Hmmm.. Some of the failures are because MockAssembly.dll is being loaded in and run.
I know I'm due an opticians appointment, but I couldn't see a way to exclude via .RunSettings

https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NUnitTestAdapter.cs#L147

**Comment by ChrisMaddock** [comment]
My understanding is that we've never formally supported running the NUnit tests themselves in the adapter. My opinion would be that if there's no good reason for that, then a PR to improve it would be welcome - although other team members may disagree!

--------

> Hmmm.. Some of the failures are because MockAssembly.dll is being loaded in and run.
I know I'm due an opticians appointment, but I couldn't see a way to exclude via .RunSettings

You're correct - there currently is no method to exclude the assembly. Take a look at the tail end of this PR, from when @jnm2 proposed the same idea for the framework tests. https://github.com/nunit/nunit/pull/2297#issuecomment-334939925 My personal preference is allowing the test adapter to provide the `--skipnontestassemblies` option (or more, have it on by default) - but that hasn't yet been discussed or implemented.

**Comment by CharliePoole** [comment]
Anyone creating an application may choose to require their tests to be run in a particular way. The NUnit tests are designed to run under the console runner. There are limitations in the VS environment that would normally prevent some tests from running unless the tests themselves were runner-aware. I've never been in favor of that sort of thing - it's analogous to what the VW engineers did in order to pass California emission tests.

@nunit/framework-and-engine-team I'd close this as won't fix if I were you guys. If you actually want to do something about it, it appears to belong in the adapter repo, not the console.

**Comment by alski** [comment]
#349 Fix the tests, but Mock assembly still called.

**Comment by alski** [comment]
@CharliePoole Good call. 

Interestingly I thought I would test this out and was surprised to see that

C:\Dev\nunit-console\bin\ **Debug**>nunit3-console.exe nunit.engine.tests.dll
  Test Count: 516, Passed: 510, Failed: 0, Warnings: 0, Inconclusive: 5, Skipped: 1

and 
C:\Dev\nunit-console\bin>**Debug**\nunit3-console.exe **Debug**\nunit.engine.tests.dll
  Test Count: 516, Passed: 510, Failed: 0, Warnings: 0, Inconclusive: 5, Skipped: 1

where I would have expected the latter to fail!

**Comment by rprouse** [comment]
We got the tests running in the adapter in the main NUnit solution and ignored the mock assembly and the testdata assembly. @jnm2 I forget what you did to get those projects ignored for testing. Do you remember?

We did design the tests to run under the console and that is what we use to verify our tests, but I have found including the adapter in the NUnit project to be useful. It allows us to dog food the adapter and it is also an easy way to run and debug individual tests without messing with project settings and command lines.

**Comment by CharliePoole** [comment]
I'm big in favor of dog-fooding! However, I'll respectfully point out that if you are working on the framework team, running under the adapter is precisely the __opposite__ of dogfooding. In fact, so is running your tests under the console, since that's a separate product.

Of course, our disagreement on this is long-standing and I'm not expecting a change but I couldn't resist commenting once you used the phrase "dogfooding". 

BTW, as the original author of the VS adapter, I set it up so that it was tested under... the adapter! How about that?

**Comment by CharliePoole** [comment]
@alski It passes in both cases because of how NUnit automatically sets up the application base.

**Comment by ChrisMaddock** [comment]
Just to transfer my comment from the PR - I believe the adapter is a red herring in this situation, and the test failures @alski is seeing are actually down to the work**ing** directory. I can see the same failures from running the tests in the nunit-console, but launching the process from a different directory to the `TestDirectory`. That makes me think we should definitely get this fixed.

I didn't remember Joseph had done something to hide the non-test assemblies in the framework project. I'd be in favour of doing the same here, if possible.

**Comment by jnm2** [comment]
Dogfooding means precisely 'using your own product.' I'm working on the framework team and dogfooding NUnit.Console and ApiContractGenerator while doing so, since I work on both of those also.

@rprouse 

> We got the tests running in the adapter in the main NUnit solution and ignored the mock assembly and the testdata assembly. @jnm2 I forget what you did to get those projects ignored for testing. Do you remember?

Sorry to disappoint, but the framework is still only doing NUnitLite and self-executing tests. I hit a wall because I couldn't get the VSTest adapter to respect ExcludeAttribute within nunit.framework.tests itself.
https://github.com/nunit/nunit/pull/2380#issuecomment-346538662

**Comment by CharliePoole** [comment]
@jnm2 `<snark>`I'm sure glad you explained that.`</snark>`

The reference was probably too obscure for this forum, since it refers to private conversations Rob and I have had. Sorry 'bout that. My point is that the original goal was to make framework console and adapter separate - a goal that I feel I failed at.

**Comment by jnm2** [comment]
@CharliePoole When awkward conversations are made public, I'm likely to stick up for the guy that _appears_ to be unfairly treated, purely at face value since I have zero information about the private context. I might also take the smarter policy for my own sake and pretend it wasn't happening. I never know which is better.

**Comment by mikkelbu** [comment]
@ChrisMaddock Is there anything left in this issue? As far as I can tell the PR solved the original problem.

**Comment by ChrisMaddock** [comment]
I believe the mock-assembly tests were still included under the adapter, and we were considering making the adapter understand ‘NonTesyAssemblyAttribute’ to avoid that. That perhaps should be a separate issue though.

On my phone at the moment, so afraid I can’t search in more detail!
