### ISSUE TITLE
CommandLineOption --err does not write error input to ErrorFile

### ISSUE THREAD

**Issue by Tyonoro** [nunit/nunit-console#360]
Hi guys,

I am trying this:
"nunit3-console.exe MyTestAssembly_uTest.dll --err=ErrorOutput.txt --out=StandardOutputfile.txt"

The assembly to test has only one test:
```C#
public void SampleTest()
       {
            Console.Error.WriteLine("I am a standard error output.");
            TestContext.Error.WriteLine("I am a standard error output.");
        }
```
After execution of the test case above, the file which should contain the error output is always empty. 
I realized that the strings are written to the StandardOutputfile.txt.

Can you help me guys?

**Comment by rprouse** [comment]
Sorry, looks like a bug. Those options aren't used much or well tested. Labelling as confirm so I make sure that is how it is supposed to work.

**Comment by rprouse** [comment]
@Tyonoro I started looking at the code for this and as far as I can tell, it has never worked in NUnit 3. We color error output red and we create a file for the error output, but we never use the error writer that is created, it isn't even passed into our `TestEventHandler`. It will take a bit of plumbing, but it shouldn't be too hard to fix.

**Comment by CharliePoole** [comment]
An extreme variation that would "fix" this is to simply remove the `--err` option. That's extreme, but if it has actually never worked and this is the first report we've had, it may make sense. Probably we should test with some earlier 3.x releases though. It could have become broken when we were working on the enhanced display of labels.

**Comment by rprouse** [comment]
@nunit/framework-team can we weigh in on this issue? My original inclination was to drop support for `--err` since it has never worked and nobody has noticed in the four years since we released 3.0 and much longer if you count the pre-release 2.9.x releases. Diving into the code, outputting to a separate file is complicated by our various label options. Should the output to an error file include labels? Is it useful without labels? If so, why do we output labels to files for standard output?

One thing that does bother me is that error output does not go to `stderr`, but is output to `stdout` colored red, or output to the output file if it is specified.

Possible options are;

1. Remove the `err` command line option
2. Implement `err` without labels
3. Implement `err` with labels before as in #366 
4. Implement `err` respecting label position (before, after, none)

I am leaning towards 1. Oddly, option 2 and 4 make the code much more complicated than it needs to be and than 3, but even 3 isn't great as you can see in #366.

**Comment by CharliePoole** [comment]
I like item 1 for error.

My thinking about the labels for stdout is that it is normally displayed... either immediately at the console or later by saving the output and viewing it in an editor. It makes little sense without labels and users have the choice to turn off labels anyway.

I'd be OK if we wanted to pick an option 2, where we send it to a file without labels. I'm surprised if that makes the code more complicated. I assumed it would just be routed to a different event handler, one that didn't know about labels at all.

**Comment by rprouse** [comment]
You are probably right about the second option @CharliePoole, it just seems to complicate `TestEventHandler`. It would be cleaner if we had an aggregating test event handler, or if `ITestEventListener` had a `ITestEventListener NextHandler` property so that they could be chained.

**Comment by ChrisMaddock** [comment]
1, 2 or 4 seem good to me. I hadn't understood properly that #366 was a partial implementation sorry - that seems like something which might cause us trouble in the future. If 2/4 are going to be non-trivial, it doesn't seem worth the effort until there's a greater user-need for it,

> One thing that does bother me is that error output does not go to stderr, but is output to stdout

Are you sure about this? I thought it was errors to stderr, meaning the redirection could be done in the console anyway.

**Comment by jnm2** [comment]
I'm not sure we should remove it since people like @Tyonoro are using it.

**Comment by CharliePoole** [comment]
@jnm2 Except he isn't successfully using it. 😄

**Comment by jnm2** [comment]
Maybe the use case exists though.

@Tyonoro If we removed this feature, what would your next best option be?

**Comment by rprouse** [comment]
My initial thought when the issue came in was to drop the `-err` command line as @CharliePoole mentioned in his comment on #366. If nobody has noticed in the many years that NUnit 2.9.x and 3 has been out, then nobody is using the option. There is also disagreement on whether error output should have labels. I think it should because we add labels for redirected `stdout`.

As I see it, the options are,

1. Drop the feature since it never actually existed
2. Allow redirect of `stderr` without labels
3. Allow redirect of `stderr` with labels before errors
4. Allow redirect of `stderr` and respect the labels command line.

4 is most correct, but the code will be excessively complex. PR #366 accomplishes 3 once I do a bit of cleanup. Personally, I'm inclined to remove the feature since even the original reporter hasn't got back to us.

**Comment by ChrisMaddock** [comment]
If we write errors to stderr, is there any reason why the user wouldn't be able to redirect on the command line instead? In which case, I'd be in favour of (1).

**Comment by CharliePoole** [comment]
Yes. And I wish I'd brought that up myself! In fact, the entire design of redirection in the console - e.g. the fact that we only redirect test output - was predicated on the notion that users can always redirect the entire command.

**Comment by rprouse** [comment]
Currently `stderr` is output to `stdout` or to wherever `-out` is redirected to. We could pass `stderr` in and write to it instead. If we do that **and** `stdout` is redirected, should we also write to the redirected output since it is all output?

**Comment by CharliePoole** [comment]
Has anyone checked to see what happens when street is redirected at the command line rather than through NUnit?

**Comment by rprouse** [comment]
I haven't, but since we are capturing output and writing everything to `stdout`, I doubt it will work. We create a `stderr` writer, but don't pass it in to the event listener.

```C#
WriteOutputLine(testName, outputNode.InnerText, stream == "Error" ? ColorStyle.Error : ColorStyle.Output);
```

**Comment by Tyonoro** [comment]
Thx for all the replies and sorry for my late answer.
For me it would be fine to drop the feature if it would be too much effort.
