### ISSUE TITLE
Synchronous Handling of a Failed Test Case

### ISSUE THREAD

**Issue by ghost** [nunit/nunit-console#417]
Hi all,

in my organization, we have the following use case:

**_As a test engineer, I want to extend NUnit in a way that a screenshot (or savelog, or ...) is captured in the moment when a test case fails, so that a developer can effectively and efficiently analyze the root cause of the failure._**

What we tried is to write a NUnit extension that implements ITestEventListener that listens to the <test-case...> event. By parsing this tag we can figure out whether the test has failed. In the failed case we can trigger my custom actions.

The big obstacle here is that NUnit test events are received asynchronously. Means that, between the time my extension receives the event and the time that my custom action (e.g. taking a screenshot) is triggered, the test thread continues and could possibly have already started the subsequent test case, and the screenshot would miss to capture the failure state. 
So this approach is not working for us.

My question would be now: 
**Do you know any possible way that NUnit can be extended such that my use case can be realized in a synchronous way?** Any ideas or suggestions in what direction we could go with further investigations?

Thanks and best regards!

Environment looks like this:
* Parallel execution of tests is not required 
• We run our tests with process model “Separate” (--process=Separate)
• NUnit Framework Version: 3.10.1
• NUnit Console Version: 3.8.0

**Comment by Tyonoro** [comment]
Hi holpstxl,

thanks for bringing up this question, I have a very similar use case in my company. 
Did you already find a solution for your problem?

While going through the nunit-console code, I discovered a 
`public static class FrameworkPackageSettings`
containing a 

```
/// <summary>
/// If true, use of the event queue is suppressed and test events are synchronous.
/// </summary>
public const string SynchronousEvents = "SynchronousEvents";
```

Hmmm, suspicious. It seemed to be a hint that NUnit is still capable to handle test events synchronously.
Doing further research, I found that this setting is used in the framework in` NUnitTestAssemblyRunner.cs `to do some event pump initialization. 

So far, so good. But how to inject this setting now into the framework without to modify the code directly?

The answer was a Custom Framework Driver Extension, see here:
[https://github.com/nunit/docs/wiki/Framework-Drivers](https://github.com/nunit/docs/wiki/Framework-Drivers)

(In short: Implement a new Framework Driver class which derives from `NUnit.Engine.Drivers.NUnit3FrameworkDriver` and implements `IFrameworkDriver`. In the `Load(…)` method, add the settings
`settings[FrameworkPackageSettings.SynchronousEvents] = true;
`and call `Load(…)` method of the base class with the altered settings.
In the `GetDriver(…)` method of your extension, return this new Framework Driver.)

I don’t know if this is the most elegant solution, but at least I could prove that test events were handled synchronously when the extension was loaded! 
If you want to have more details on how I did the implementation, just give me a note.

**I would appreciate your opinion about my approach!**

Best regards!

**Comment by CharliePoole** [comment]
@Tyonoro The setting is a contribution from a Microsoft engineer, which is never set by NUnit's own runners but is used within the NUnit3 VS Test adapter in very restricted circumstances. We accepted the contribution because Test Explorer's developers agreed that it will only be triggered in limited circumstances where it can do no harm. If you use it in a custom driver, you will have to provide that guarantee for yourself.

The setting is somewhat misnamed. Although events may be considered as synchronous when it is used, this is only true on a per-thread basis and the entire event pump mechanism is eliminated as a result.

NUnit's event pump serves two main purposes:

1. It serializes all events to a queue so that they are handled one at a time. If one event's processing should generate another event, the nested event is enqueued rather than executed. This feature only applies to event listeners within the framework, since only such event listeners can generate other events.

2. It calls the event handler on a dedicated thread, separate from the test thread. This prevents the thread call context from being serialized across remoting boundaries and possibly causing an exception if the context contains Types unknown in the receiving domain. Unlike the first item, this applies specifically to code that is outside the framework, such as engine extensions and the NUnit console runner itself.

As you can see, the event pump is pretty important to NUnit, which is why we did not make the setting that eliminates it available to users through a command-line option. If your framework driver turns it off, you have to be aware of the pitfalls and somehow avoid them in your test code and in any test listener extensions you have installed.

Essentially, the OP's original issue arises from the decision to create snapshots in an engine extension rather than within the framework. NUnit provides a way for you to add attachments to the test result, which you create in the test code or using custom attributes. That's the approach I would take.

**Comment by CharliePoole** [comment]
I believe this has been answered so I'll close it. Of course, we'll see and respond to any further comments on the question.
