### ISSUE TITLE
Support nanoserver

### ISSUE THREAD

**Issue by Kuinox** [nunit/nunit-console#420]
Hi,
I'm trying to run unit test in a docker container with the image dotnet:2.0-sdk(it's using the nanoserver)
But there is missings ddl, can the nunit-console support nanoserver natively or it's not feasible ?

**Comment by Kuinox** [comment]
dotnet test doesn't output a XML file that i need to parse the unit test results.  
I dont know which dll it complain, the nanoserver make the binary silently fail.
To scan the missing dll, microsoft give a tool that do it, but i didn't managed to make it work(https://blogs.technet.microsoft.com/nanoserver/2016/04/27/nanoserverapiscan-exe-updated-for-tp5/), i didn't found the binaries of the command.

**Comment by rprouse** [comment]
If I am correct, the issue is not that we don't support NanoServer, but that we do not have a .NET Core version of the console runner and/or the `dotnet test` command does not produce NUnit test results.

We have issues for both of these already, so i am going to close this issue. Please let me know if I am mistaken.

In the meantime, you can get VSTest results from `dotnet test`, see https://github.com/nunit/nunit3-vs-adapter/issues/323
