### ISSUE TITLE
NUnit console does not exit automatically after all unit tests passed at the end.

### ISSUE THREAD

**Issue by AudreyHui** [nunit/nunit-console#429]
Hi All, 

I found a strange issue,  when we select a group nunit tests to run and make all of unit tests are passed, as we have ended all of unit test, so I think the unit-console should be exited automatically, but it doesn't , we still can find it in task manager, as we have a lot of unit test need to run, so we have 6 groups, but it always stop in one of groups lead to the rest of unit test cannot be run, would you have a look at, or give an solution.

And also if we can kill the task in task manager, and then restart the machine, it can be resolve and all of unit test can be completed. but I think it doesn't make sense, please give me a help, thanks!

**Comment by siprbaum** [comment]
Are there perhaps any Threads spawned, which don't have the `IsBackground` set to `true`?
If have seen this from other console applications that they don't terminate if there is still some
foreground thread running.

**Comment by AudreyHui** [comment]
No,  we haven't set the IsBackGroud to true.

**Comment by ChrisMaddock** [comment]
Which version of the console are you using? This sounds like a bug we fixed in a recent version.

If you're already on latest - can you run with `--trace=debug` and share the logs?

**Comment by ChrisMaddock** [comment]
Also, which process isn't terminating. The NUnit console itself, of the nunit-agent process?

**Comment by jonathanpeppers** [comment]
I just filed #430 could it be related?

I have a lot more information there.

**Comment by AudreyHui** [comment]
Thanks all.

The version is 2.5.9.10348, I have got a summary from nunit-console, therefor, I think the unit test has completed, but the nunit-console still in progressing. I have attached screenshot about task manager and unit test result, please help me have a check. And also for this version, how to get the log files? if this is a bug which your have fixed it recent version, I need to update it to latest version? Perhaps the update will lead to a larger migration, do we have any other solutions? thanks!

![result](https://user-images.githubusercontent.com/34882203/41577939-368703a8-737f-11e8-998a-9e861a324171.png)
![console](https://user-images.githubusercontent.com/34882203/41577940-393eeac0-737f-11e8-8f6b-6525856bf319.png)

**Comment by ChrisMaddock** [comment]
Ah - you didn't mention you were using NUnit 2!

NUnit 2.x is no longer developed but the NUnit organisation - we're focusing on NUnit 3.x - however @CharliePoole has been doing some work on the v2 product here: https://github.com/nunit-legacy/nunitv2

In the long run, I'd absolutely recommend upgrading to NUnit 3 which has various new features and benefits. You're correct that may be a larger migration however - so in the interim, you may just wish to try upgrading to the latest version of NUnit 2.x (v2.6.6 - available from the repository above!), and see if that solves your problem.

I'm going to close this issue, as, at the moment, there's no issue to be fixed in the current version of the software. If you upgrade to 2.6.6 and still see this problem - you could try raising the issue in the nunit-legacy/nunitv2 repository. If you upgrade all the way to the latest NUnit 3, and still see the problem, let us know, and we should have a better idea of how to debug it!
