### ISSUE TITLE
Running tests written with NUnit and Telerik Testing Framework using nunit-console or nunit-gui

### ISSUE THREAD

**Issue by magierska** [nunit/nunit-console#463]
I want to run tests in nunit-console. I wrote tests using NUnit 3.10.1 and Telerik Testing Framework. When I run them using Visual Studio 2017 Test Explorer with NUnit3TestAdapter 3.10.0 installed everything works fine. But when I want to run them through nunit-console or nunit-gui all of them fail. I checked that Telerik Testing Framework can find window, even check values in textboxes, comboboxes etc, but when I want to click somewhere, mouse doesn't move and anything happens. 
Also I noticed that after running tests via nunit-console or nunit-gui Google Chrome works different: when I want to change tab by clicking on it - it closes, when I want to go back - previous page appears in new tab. I assume that my mouse settings were changed in some way. None of this happened, when I ran tests from Visual Studio.
Do you have any idea, what can I do to run them successfully?

**Comment by magierska** [comment]
Sorry, I meant that I am using nunit3-console.exe and nunit-gui downloaded from choco. Are they compatible with NUnit 3?

**Comment by CharliePoole** [comment]
NUnit3-console is compatible. It's part of NUnit 3. NUnit-gui on chocolatey.org has been renamed as the TestCentric Experimental Gui, although no new release has been made.

It hasn't been worked on since last year and won't be developed further until after the release of the (non-experimental) testcentric gui, which is `testcentric-gui` on chocolatey. Latest releases of the two packages are:

    testcentric-gui      1.0 alpha 
    nunit-gui              0.6 (pre-alpha, experimental code)

I'll make a note to change the description of nunit-gui on chocolatey.org.

If you are unable to run something on the nunit3-console, it is not going to work on the gui either. So you should work with the console first. We can try to resolve your problem on this issue if you are able to provide some sample test code that is not working.

**Comment by magierska** [comment]
I have created example test project: [ExampleTest.zip](https://github.com/nunit/nunit-console/files/2339827/ExampleTest.zip)
When ran from Visual Studio all 2 tests are passing, but when ran from console, ClickButton test doesn't pass. We can see, that there is no problem in finding window or changing text in TextBox, but when we want to move mouse or click, nothing happens.

**Comment by rprouse** [comment]
@magierska the tests that you uploaded do not run on my machine with the error,

```
1) Error : CalculatorTest.Test1.ClickButton
System.IO.FileNotFoundException : Could not load file or assembly 'Telerik.TestStudio.Core, Version=2018.2.606.0, Culture=neutral, PublicKeyToken=4fd5f65be123776c' or one of its dependencies. The system cannot find the file specified.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at ArtOfTest.WebAii.Core.Manager.CreateLog(Settings settings)
   at ArtOfTest.WebAii.Core.Manager.Init(Settings settings)
   at CalculatorTest.Test1.SetUp() in C:\src\spikes\ExampleTest\ExampleTest\Test1.cs:line 24
--TearDown
   at CalculatorTest.Test1.TearDown() in C:\src\spikes\ExampleTest\ExampleTest\Test1.cs:line 34
```

I assume that I need Telerik TestStudio installed which I won't do.

Usually when testing UI applications like this you need to run the tests in an STA thread. To do so, add the attribute `[RequiresThread(ApartmentState.STA)]` to your test class.

I am going to mark this as a question and close. This is a problem with the interaction of NUnit and Telerik TestStudio which we know nothing about. Usually we ask that people ask questions like this to the higher level framework. Feel free to post more comments here even though the issue is closed, we will see them.
