### ISSUE TITLE
[Question] Which parameters are good to use durning parallel tests ?

### ISSUE THREAD

**Issue by testingplusme** [nunit/nunit-console#472]
Hey Guys, 
I have approximately 300 E2E (Selenium) in SpecFlow and NUnit and I'm running it by NUnit Console Runner something like this:
`.\nunit3-console.exe --workers=4 --inprocess --dispose-runners --params:BrowserName=Chrome --params:BrowserVersion=63.0 C:\MyTests.dll  `
I have a problem that approximately 1% or 2% of tests are almost always failed when I'm running a bunch of tests. When I run this tests they're passing. I'm trying to find a reason. Maybe I shouldn't use `--inprocess` or `--dispose-runners`?

I know that it could be flakiness as the reason but very often is another test not the same so it looks like  100% is difficult to achieve in parallel but when I run tests alone these test it works perfectly. Previous when I had fewer tests e.g. 100 I could have it (100% of passed tests)
Just I'm thinking about the solution:
1) Maybe I should take the name of tests from XML and run it e.g. for 10 parts?

I rejected the option as a rerun because I wanted to have stableness but I don't know what I can do yet to achieve this. If you have any ideas I will happy to hear about it.
Cheers,
Michal

**Comment by CharliePoole** [comment]
The `--inprocess` option forces your tests to run in the same process that hosts NUnit, rather than in a separate process as is normally done. Just like all NUnit options, you should use it if you have a good reason to, otherwise don't. The NUnit defaults should normally be your default.

The `--dispose-runners` option has no purpose when used with the `--inprocess` option. It's an advanced option that can be used to improve efficiency when running many different test assembiles, each in a separate process, while also limiting the number of active runners with the `--agents` option. Since you have only one assembly and a small number of tests, you have no need for it.

You specify `--workers=4`, which has two consequences:

1. You will get four parallel threads in which tests __may__ be executed. Whether or not your tests actually run in parallel depends on your use of the `ParallelizableAttribute`, which you have not mentioned.

2. You will __always__ get four parallel threads, no matter what computer you use that command-line on. It could be a machine with 64 cores or one with only one core! So if you don't want the default number of threads, you may need to change the command-line for each machine you use.

You need to provide more information about whether you are actually running in parallel. Of course it is possible for parallel or non-parallel tests to interfere with one another, but they do it in different ways. Interference from other tests is the probable cause of your 1% to 2% failure rate.

**Comment by testingplusme** [comment]
@CharliePoole Thank you. I'll remove these parameters :) 

> You specify --workers=4, which has two consequences: 

 Ofc, it's was the only example I take the variable from Jenkins where I can control how many threads I want during my tests. I have something like that:
`--workers=%NUMBER_OF_AGENTS%`
In a project with tests I'm using these settings for a parallel run:
```
[assembly: Parallelizable(ParallelScope.Fixtures)]
[assembly: LevelOfParallelism(2)]   
```
I was wondering about interference, but rather it's performance of server when 4 threads are running. Selenium is quite heavy.

**Comment by CharliePoole** [comment]
LevelOfParallelism attribute and --workers option on command line perform the same function. They specify number of threads.

NUnit --agents option is used to limit the number of processes running. I'm not familiar with the Jenkins setting.

With your settings fixtures will run in parallel, which is s conservative and usually safe strategy.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
