### ISSUE TITLE
nunit console runner only running x86 instead of x64

### ISSUE THREAD

**Issue by MPasadu** [nunit/nunit-console#529]
These are the arguments I use

> --agents=1
> --workers=1
> --config=Debug
> --labels=On
> --wait
> --skipnontestassemblies
> --testlist=\TempTests.txt
> {path to .sln file}

The solution file has configurations for `x86` and `x64` projects. Running it like this, the console runner only tries to find the `.dll` inside the Debug folder, which then fails because there is nothing in there.
All our tests are written in` x64`, so is there any way to make the console runner force look at the `/Debug/x64` folders?

I think this issue might be related to this one: https://github.com/nunit/nunit3-vs-adapter/issues/384

**Comment by CharliePoole** [comment]
The console runner relies on the engine to find the executables. The engine, in this case, relies on the Visual Studio Project Loader extension. The extension __should__ be returning the output directory that is specified for each project, for the config you specify. If you have separate configs for x86 and x64, then they must have separate names, which you should use of course. OTOH you may have just one config being built for separate platforms. In that case, I __believe__ NUnit should be using a config name like "Debug-x86" but I would have to check the code to be sure.

Please let us know what versions of the console runner, engine and VS loader extension you are using. 

The issue you site was in the repository and was moved to #286 in this repository.

**Comment by MPasadu** [comment]
I am currently looking over our Active solution platform settings, and it seems we have multiple different active solution platforms configured in which the projects's platforms are different. 

I am not sure if I understood correctly, but setting the config **and** the active solution platform should be a thing? Or does the console runner just run all the active solution platforms specified in a config?

**Comment by CharliePoole** [comment]
OK... I checked the code to find an answer... bear in mind that I wrote this __many__ years ago and it has been changed a lot since then. IOW take this with a grain of salt. :-)

A "config" in the context of the `--config` argument only applies to projects (like VS projects or solutions, NUnit projects, any other type that may be defined in the future). It's actually up to each project loader extension that supports configs to define what a "config" is for it. This is important, as you will see in the following.

For the VS project loader extension, a "config" is a combination of a visual studio configuration and a platform. So, for example, "Debug|x86" would be a config. The config "Debug" actually means "Debug|AnyCPU". One result of this is that you can't ask to load __both__ the x86 and x64 versions of the Debug build of an assembly. This is built into the project loader and you can't change it... that is, you would have to file an issue against the loader and ask for an enhancement of some kind.

For an NUnit project, a config can be anything you want it to be.. it's just a string that causes a particular list of tests to be loaded. If the VS project loader does not do what you need, then you may consider creating an NUnit project for your solution, which specifies the exact combination of assemblies you want to run. So, for example, you could create a "Debug" config that listed the locations of both the x64 and x86 builds of some assembly. If that is what you are trying to do, then I would say that using an NUnit project is the way to go.

**Comment by MPasadu** [comment]
That makes sense! Thanks for looking into it!

I tried running with "Debug|x64" because I only want to run this config:
https://imgur.com/a/7DP51oD

But now I get the `File Type is not supported` error on the .sln file.
I guess that's because the config does indeed include x86 platforms as well as x64, however the x86 are all not checked for building.

**Comment by CharliePoole** [comment]
In that case, I suggest setting up "configs" that work for you.

1. Create a name for each grouping of test assemblies you want to run together.

2. Either manually or using the NUnit Project Editor download, create the XML that represents an NUnit project. See an example at http://nunit.org/files/nunit_project_25.txt but you can leave out most attributes (except for the config and assembly names, of course) until they are needed. Note that the assembly paths are relative to the location of the .nunit file itself. An assembly can appear in more than one config if you need to run differing combinations.

I suggest starting simplly. :-)

**Comment by CharliePoole** [comment]
Also... here is the documentation of the format

https://github.com/nunit/docs/wiki/NUnit-Project-XML-Format

**Comment by MPasadu** [comment]
Thank you I will try it!

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
