### ISSUE TITLE
Tests in inputfile for --testlist argument not recognized/not run

### ISSUE THREAD

**Issue by ccarmannt** [nunit/nunit-console#541]
When running a set of tests using the `--testlist` command line argument, tests are not recognized/not run.
The same tests are recognized and run when using the `--where` command line argument.

For example, if I have a test named `test1234` in a class named `Beta`, these test names work from `--where` but not from inside a file for `--testlist`:

````
--where=test=~test1234
--where=test=~Beta.test1234
````

In the input file, the names are listed like this:

````
test1234
Beta.test1234
````

**Comment by mikkelbu** [comment]
Hi @ccarmannt
What happens if you fully qualify the test names in the input file? (meaning also specify the namespace)

**Comment by ccarmannt** [comment]
I tried that and found that if I include the full namespace prepended to the class and method, the test is recognized and run as expected.

**Comment by mikkelbu** [comment]
@ccarmannt I'm closing this issue as answered. I've you disagree or have additional comments, then just write in the issue and we will see the comments.

**Comment by ccarmannt** [comment]
This is a bug that needs fixing. --where and --testlist should accept the same list of tests.

**Comment by mikkelbu** [comment]
As far as I can tell they behave in they same way, just for the equality operator.

In `--where=test=~test1234` you are using the `=~` operator meaning that the right hand side specifies a regular expression that the test name should match (see e.g. https://github.com/nunit/docs/wiki/Test-Selection-Language). `--testlist` takes a file which contains a list of named tests, so here there the comparison is equality.  So `--testlist` behaves similar to a `--where` where you specify an exact match (either using `=` or `==` as operator).

**Comment by ccarmannt** [comment]
Why should there be any difference between the two? There shouldn't.

**Comment by mikkelbu** [comment]
The reason for why they are different is because you are using two different kinds of matching. In `--where=test=~test1234` you are using regular expression matching and not equality. If you had used equality matching in the where, like `--where=test=test1234`, then that would also not match the test unless you specify the fully qualified test name.

General speaking the "test selection language" following a `--where` is much more general than what is available for `--testlist`, and the selection language supports many kinds of comparisons (equality, inequality, regular expression, ...). So the two different approaches work the same - or at least should work the same - if you use equality matching in the `--where` expression.

**Comment by CharliePoole** [comment]
As @mikkelbu says, test selection language is much more general. It's also newer. The --realist option has been around for about 10 years and is maintained for backward compatibility.

If you want to put TSL in a file, that's also possibly using the @ notation.

**Comment by ccarmannt** [comment]
If I try to put TSL in a file using @ notation, only the second where clause gets processed:

--where "test =~ the1"
--where "test =~ the2"

Test Filters
    Where: test =~ the2

**Comment by CharliePoole** [comment]
You used two --where options and the last entered was used. Same would be true if you did it on the command line.

Instead, you want 

--where "test =~ the1 || test =~ the2"

Alternatively...

--where "test =~ the[1|2]"

Or similar regex expression.

**Comment by ccarmannt** [comment]
Thanks for the description. I've verified it works as an alternate solution.
