### ISSUE TITLE
--labels=Before ignores --nocolor

### ISSUE THREAD

**Issue by bohni** [nunit/nunit-console#547]
When using --nocolor the output of --labels still is colorized.

**Comment by ChrisMaddock** [comment]
Thanks @bohni - verified by looking at the code. A pull request to fix this one would be very welcome, if you'd be interested?

For anyone interested, the problem lies in [TestEventHandler](https://github.com/nunit/nunit-console/blob/f98bd132d9bd25330e3cbf996571414b68b582b6/src/NUnitConsole/nunit3-console/TestEventHandler.cs) - this class has no awareness of the `--nocolor` option. It should have that information passed in to the constructor. Note that this also affects all other `--labels` options, not just `Before`.

It would also be great if this could be backed up by a unit test...although I haven't totally looked into the feasibility of creating a mock inheriting TextWriter, to do this! 😄

**Comment by CharliePoole** [comment]
Someone should look a little deeper, I think. The `TestEventHandler` class was never aware of anything regarding how the output is actually created. The TextWriter that is passed to the constructor took care of all that originally so I suspect that has somehow changed.

If possible, it will be better if the use of color or not remains encapsulated in the `TextWriter` or `ExtendedTextWriter` we pass as an argument. One example of where this is important is when we are spooling the output to a file.
