### ISSUE TITLE
Is there a plan for a release of 3.11?

### ISSUE THREAD

**Issue by Birgos** [nunit/nunit-console#554]
We use NUnit 3.11 in our project and **NUnit-Console-Runner** 3.9.0 for our **continuous integration** process.

For the CI process, we have created an own NuGet package, which has dependencies like MSBuild tools and various analyzer packages. The NUnit Console Runner 3.9.0 is also a dependency of this package.
When we install this Buildprocess NuGet package in Visual Studio, the **references of NUnit Console Runner** and its dependencies (mono.cecil, nunit-agent, nunit-agent-x86, nunit.engine, nunit.engine.api) are also **added next to the existing NUnit** reference (nunit.framework).

Unfortunately, we then get **errors** in the test runs, because the **different versions** seems not to be compatible.

Our currently **workaround**: manually removing the references installed by NUnit-Console-Runner 3.9.0 after installing the NuGet packages.

So I wanted to **ask if a release for version 3.11 is planned** in the near future that **only depends on nunit.framework** and could renounce nunit.engine - or if maybe someone knows a better solution?

**Comment by CharliePoole** [comment]
NUnit console uses the engine to locate and run tests. The engine essentially provides all the functionality needed by __any__ runner in order to discover and execute tests. It is used by the console runner, the VS adapter and the TestCentric GUI among other things. 

Also, the runners and engine do not have a reference to the framework, so if there is a version problem it isn't likely to be between the engine and the framework. As separate software packages, the version numbers for the engine and the framework are not related to one another. The 3.9 engine can run tests built against the NUnit framework versions 3.0 through 3.11 as well as future releases unless we change the API. If you provide more info on the kinds of errors you are getting, then someone can probably help you figure out the source of the version conflict.

**Comment by Birgos** [comment]
We embarrissing missed to see that a dependency of the NUnit 3.9 framework had "crept in". After we removed it everything worked as expected.
Thank you very much for the clarification and the insanly fast support!
