### ISSUE TITLE
Test returns -2 even if all pass and --skipnontestassemblies is written

### ISSUE THREAD

**Issue by marcusl** [nunit/nunit-console#581]
Hi,

Reading through other (various related) bugs I realize I should try and provide a minimal repro case. I will try to do so.

In the mean time, this is what I'm running:

`>nunit3-console.exe Cpac.Eol.sln --skipnontestassemblies --labels=before --where:"cat != HardwareTests" --result="C:\Dev\cpac-eol-C#\nunit-report.html";transform="C:\Dev\cpac-eol-C#\Scripts\\nunit-templates\html-report.xslt"
`

And the end of the output is this:

```
Errors, Failures and Warnings

1) Invalid : Cpac.Core.dll
Has no TestFixtures

Run Settings
    DisposeRunners: True
    SkipNonTestAssemblies: True
    WorkDirectory: C:\Dev\cpac-eol-C#
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.7.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 3

Test Run Summary
  Overall result: Failed
  Test Count: 22, Passed: 22, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-03-21 12:42:27Z
    End time: 2019-03-21 12:42:48Z
    Duration: 20.337 seconds

Results (user) saved as C:\Dev\cpac-eol-C#\nunit-report.html

=== Unit tests failed return code: -2 ===
```

Is it because I have NUnit references in the core dll? (I have a utility class there)

Will test and att a small test fixture there, to see if that's the problem

I love nunit btw! :-D

**Comment by CharliePoole** [comment]
If `Cpac.core.dll` references the nunit framework,make sure it's the same version as your tests, if they are all in the same output directory.

Here's the thing though. The definition of a "non-test assembly" is one that __doesn't reference the NUnit Framework__. So, `Cpac.core.dll` looks like a test assembly and is not skipped.

There's a way to avoid this, however. The `NonTestAssemblyAttribute` is right there in the framework for you to use. Because of it's limited intended audience, we never listed this in the docs but the doc comments should tell you all you need to know...

```C#
namespace NUnit.Framework
{
    /// <summary>
    /// Used by third-party frameworks, or other software, that reference 
    /// the NUnit framework but do not contain any tests. Applying the 
    /// attribute indicates that the assembly is not a test assembly and 
    /// may prevent errors if certain runners attempt to load the assembly. 
    /// Note that recognition of the attribute depends on each individual runner.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
    public class NonTestAssemblyAttribute : NUnitAttribute
    {
    }
}
```

**Comment by marcusl** [comment]
Indeed. Thanks a lot! 

Keep up the good work!
