### ISSUE TITLE
Remove multiple possible TestPackage structures for "single item" packages

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#598]
TestPackage current has two constructors:

```
public TestPackage(string filePath)
public TestPackage(IList<string> testFiles)
```

This means, that if you are creating a test package with a single file, you could do it one of two ways:

```
public TestPackage("tests.dll")
public TestPackage(new [] { "tests.dll" })
```

This is part of our public interface, and not particularly a bad thing. This issue it causes however, is that it creates two different internal TestPackage structures for 'the same thing', both of which the engine needs to handle*.

```
public TestPackage("tests.dll") creates...

TestPackage Name: "tests.dll"
   SubPackages: []
```

```
public TestPackage(new [] { "tests.dll" }) creates...

TestPackage Name: null
   SubPackages: [TestPackage Name: "tests.dll"]
```

I'd like to rework the internals of TestPackage, so that it always creates TestPackages in the second structure, regardless of the version on constructor used.

Does anyone foresee any potential compatibility problems with this? I don't think either the console or adapter would be able to see any changes caused by this difference in behaviour. (Console always uses the list ctor, adapter doesn't load projects or use process settings) Concern is more external runners - @CharliePoole, have you encountered this at all with the GUI?

---------------------
* #514 revealed that the two different package structures result in different test runner structures in a number of cases. I haven't checked, but I would imagine that projects don't work at all in the single-file-constructor format.

**Comment by CharliePoole** [comment]
I think it would be fine if the the packages passed to the engine were only constructed using the list format. In fact, we rely on that format, a so-called anonymous package, to represent the virtual package that is encapsulated by the command-line. Of course, we could do something else but it would be a breaking change.

However, when a project loader extension is being used to expand a project, it creates a number of subpackages using the single-arg constructor. See https://github.com/nunit/nunit-project-loader/blob/master/src/extension/NUnitProject.cs#L87 and https://github.com/nunit/vs-project-loader/blob/master/src/extension/VSProject.cs#L121

Since both the client and the extensions are in separate assemblies, they need public constructors. We could modify our extensions to construct packages some other way, but the single-item constructor seems to express most clearly what they are doiing: adding a subpackage that represents a single, named assembly.

Given that users may call the runner with a single-item constructor, I think the most sensible thing to do is to make it work correctly. They are only able to specify the package in one call, so we could simply detect it and transform it into our desired format at that entry point.

**Comment by ChrisMaddock** [comment]
Thanks Charlie, I wasn't aware of that case. Will have a think at some point.

**Comment by ChrisMaddock** [comment]
@CharliePoole I agree, given the API we currently have, we need to make this work. Closing this and filing #615 for the issues...which after further evaluation, I think are low priority. I'll try this with projects once a few more open PRs are in place...that may raise the priority.

Thanks for your thoughts!
