### ISSUE TITLE
Consider expanding projects before building ITestRunner structure

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#617]
Currently, the MasterTestRunner builds the tree of ITestRunners, before expanding projects. (Done inside `InitializePackage()`.

https://github.com/nunit/nunit-console/blob/23fff2b0153f8cd238cea1ea8409b87d95e6def6/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs#L83-L85

This complicates both the `ITestRunnerFactory`'s, as code must consider whether both whether a package has subpackages, or is an unexpanded project. I think it might also be the underlying driver of a few bugs, such as #29.

Is there any reason not to expand to projects before building the ITestRunner tree? @CharliePoole - I think this is your area...any thoughts? This would be sorta inline with your recent PR https://github.com/nunit/nunit-console/pull/596

**Comment by CharliePoole** [comment]
Yes, we've slowly been moving toward this, although it's not true that Master tesT runner builds the __entire__ tree of runners. I think the exceptions are important:

1. MTR can't build the runners that are used in a separate process. The remote runner in that process works as a sort of "local" MTR for that purpose, based primarily on the App domain setting for the packages. We can't change this.

2. MTR defers selecting lower-level runners to AggregatingTestRunner when projects are present. That's because projects may contain settings that impact runner selection. This is the part I think we should fix next.

I'm doing this on my phone, so it's not easy to dig deeper right now. Hope to be able to set up the laptop again later today.

**Comment by CharliePoole** [comment]
I haven't tried it, but examining the code it appears that InitializePackage could easily be called before the top-level runner is set. The initialization doesn't seem to depend on the runner at all.

As a slightly bigger step, we could consider postponing creation of the engine runner for the MTR until the Load call. In fact, two of the runners already do this.

The only drawback is that it may require changing some of the tests.
