### ISSUE TITLE
Is this compatible for .netCore 2.0 with cake script

### ISSUE THREAD

**Issue by vbpradeep** [nunit/nunit-console#620]
1. I am using .NetCore 2.0 based application.
2. i needs to run testcases in console with cake script is this compatible for core projects? if yes please give some reference or sample codes. 

i have faced below mentioned issue. 

https://github.com/nunit/nunit-console/issues/487

**Comment by rprouse** [comment]
@vbpradeep to run .NET Core tests you need to run them with `dotnet test` or as NUnitLite self-executing console apps. Since you are using Cake, I'd suggest looking at the various Test tasks here, https://cakebuild.net/dsl/dotnetcore/, most likely this task, https://cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/8191BBC4

I'd suggest getting your tests running with `dotnet run` on the command line first using the MS docs at https://docs.microsoft.com/en-ca/dotnet/core/testing/unit-testing-with-nunit then move on to your Cake script.

**Comment by vbpradeep** [comment]
Hi @rprouse ,

thanks i have made the changes, but i can't able to produce report format as html in this case. is any possibility to generate report in web page? If possible please give some reference here.

**Comment by rprouse** [comment]
@vbpradeep NUnit doesn't produce HTML test results although many third-party build systems do. For example, you can publish your test results in Azure DevOps build pipelines and they will produce HTML results.

See this example from our test runs, https://nunit.visualstudio.com/NUnit/_build/results?buildId=1648&view=ms.vss-test-web.build-test-results-tab

I am going to close this as a question. Feel free to continue posting, we will see it.

**Comment by vbpradeep** [comment]
Hi @rprouse ,

thank you for this well explained reply. but i had an another query, as you have said many third party had to generate html report, but have got test report from dotnettest is like **.trx** formated report only, even xml also i can generate too. but whenever search there is no other source found to convert like **trx** to **html** from cake build. can i get any reference,  thanks in advance.

Regards,
Pradeep Kumar B

**Comment by rprouse** [comment]
I generally use Azure DevOps for my build pipelines. It supports TRX
natively by adding a publish test results task. TRX is the standard format
for the Visual Studio test adapter, so most CI systems support it. It may
not be named as such in the documentation for the system you are using
though. xUnit, MSTest and NUnit all produce the same with VSTest or dotnet
test, so it should be widely supported.
