### ISSUE TITLE
[Question] Possible to set both labels=After and labels=Before

### ISSUE THREAD

**Issue by johannes-schmitt** [nunit/nunit-console#628]
We use nunit also as a framework for system tests. These tests have a long run time (by design), and I'd like to see both the moment when the test started as well as when it finished in the console output. The command line parameters _--labels=Before_ and _--labels=After_ are serving those needs, but I failed to combine them.

Is there a way to provide both _--labels=After_ and _--labels=Before_ in the command line parameter (like _--labels=Before,After_)?

**Comment by johannes-schmitt** [comment]
please add label "question"

**Comment by mikkelbu** [comment]
This is not possible. The option cannot both match the "before" and "after" constants at the same time.
https://github.com/nunit/nunit-console/blob/6a7c6bbe295e913ece678adfc5013d3c824473d4/src/NUnitConsole/nunit3-console/TestEventHandler.cs#L49-L52

This question has been asked before, but nothing has been done in this area as far as I know.

**Comment by CharliePoole** [comment]
Strange... I typed an answer and marked it closed, but the answer did not post! Thanks for answering @mikkelbu.

**Comment by CharliePoole** [comment]
If we wanted the equivalent of Before+After, while still retaining backward compatibility, the simplest thing would be to define a new option value, e.g.: Full. If we were willing to have the meaning of All change, that's also a simple possibility. Existing users who did not want All to mean both Before and After wouod have to switch to use Before instead. IMO, that's a minor breaking change at the command line..

**Comment by johannes-schmitt** [comment]
Thanks @mikkelbu and @CharliePoole for helping out. What do you think about adding support for "labels=Before,After". I personally would avoid introducing "Full" option, because I think it can be confusing having "All" and "Full" (they sound very similar).

**Comment by CharliePoole** [comment]
If we simply recognized "Before,After" textually, it would confuse users as it looks like the comma is a special separator. 

OTOH processing a separator makes things complicated because some combos are redundant and others illegal.

My first choice at this time is to redefine All. My second choice if folks don't want to break All is to use something else like Full, Both or BeforeAndAfter.

I think All was an unfortunate early choice that meant "All Tests" not "All Options." I hope that most people have switched to Before but if not they will merely get more output.

**Comment by CharliePoole** [comment]
IIRC when we introduced Before we said we were phasing out All.

**Comment by johannes-schmitt** [comment]
If All (=Before) should be discontinued, should we also remove On (=After)?

**Comment by CharliePoole** [comment]
On doesn't mean After. It means Label all output. Tests with no output don't get labelled.

Maybe I should write a history of this option. :smile:

**Comment by johannes-schmitt** [comment]
Sorry, I misread the docs - again (not the first time) :)
Would it be fine if I start the work on redefining All (and have a breaking change)? Or would it need more discussion?

**Comment by ChrisMaddock** [comment]
I would favour `BeforeAndAfter` - given the history here, anything else is becoming a little ambiguous!

**Comment by CharliePoole** [comment]
Here's the history...

Originally, we displayed text only... whatever the test wrote. Output from multiple tests came out one after the other without any indication of the test unless the user wrote a label.

We added the `--labels` option, which originally took no arguments. If you specified `labels` then any test that produced output was labeled first, with the full name of the test.

Some users wanted to see labels for all tests, whether they produced output or not. This could be handy in knowing which test got hung in a loop, for example. So we gave `--labels` a value: On, Off or All. All meant "Show labels for all tests" and was more or less unambiguous at the time.

Meanwhile, NUnit3 came along, with parallel execution. We modified "On" behavior so that the label was printed whenever the test doing the output changed. Of course, we had to do the same thing for All, in case you had specified it in a situation where parallel tests produced output. So "All" came to be a superset of "On" - or to imply "On" if you prefer to think of it that way.

We then added "After" for those who wanted to see the result of each test. Now "All" was ambiguous. Did it mean "On" plus "After?" Or did it mean "All tests" as before. We realized that "All" was now a bad choice so we invented "Before" with exactly the same behavior as "All". I think (but I'm not sure) we announced that "All" would eventually be removed or redefined.

The combination of Before and After, as far as I can see, is the only combo that is not available. Everything except Off already implies the behavior of On. And of course Off can't be combined with anything.

Technically, making All mean Before+After is a breaking change, at least by some definitions of breaking. At least one person in the world will complain if we do it. However, it's merely a command line option, so all you have to do is change your script or change what you type. And if you fail to do so, the only bad that happens is that you get the same output as before __plus__ the final result display. Personally, I would change it in a heartbeat to get away from having to explain to people what All means, something we have been having to do for years.

The history is interesting, but if you have to understand the history to understand an API, then I don't think it's a very good API any longer. My two cents.

**Comment by johannes-schmitt** [comment]
Just created a pull request, adding option BeforeAndAfter.
Should we add label "improvement" here?
Who is going to review the pull request?
How will documentation be updated?

I'm quite new to the process, so sorry for the many questions :)

**Comment by mikkelbu** [comment]
Answering the questions :)

> Just created a pull request, adding option BeforeAndAfter.
> Should we add label "improvement" here?

I can do that, but I think we should also figure out whether we should go with BeforeAndAfter or All. I'm on Charlie's side and think we should redefined All.

> Who is going to review the pull request?

Anybody, but it requires two committers (people with write access to the repository) to accept the PR. Currently, I think most PRs are reviewed by a handful of people.

> How will documentation be updated?

Manually afterwards. Sometimes an issue is created in the docs repository as a note that we need to update the documentation, and sometimes this first happens when people note that the documentation is not up-2-date.

> I'm quite new to the process, so sorry for the many questions :)

No problem :)

**Comment by CharliePoole** [comment]
Changed this from a question to an enhancement and added `design` label. Fundamentally, we only need to decide what we want the option to be and whether we will eliminate the old use of `All` as equivalent to `Before`.

**Comment by CharliePoole** [comment]
BTW, whatever we do here, we should do the same thing for NUnitLite.
