### ISSUE TITLE
Console runner unexpectedly aborts due to filtering on non-V3 tests

### ISSUE THREAD

**Issue by jlewin** [nunit/nunit-console#65]
When using command line filtering, specifically the "class = n" clause, nunit3-console reports the following error:

>Filtering on class is only valid when running NUnit 3 tests

Every indication I have as an NUnit user suggests I have Nunit3 tests:

- All NuGet bindings in all projects are upgraded to the latest NUnit3 builds
- No build warnings indicate a fallback to V2 mode
- No TestAdapter Test log details  indicate a fallback to V2 mode
- I was unable to find technical details regarding V2 versus V3 driver selection to further investigate the claim

**Primary Problem**
The reported error suggests a condition (non-V3 tests) that I cannot confirm or change. I can find no tools to provide insight into how the runner and engine determine V2 versus V3 driver selection and ultimately as an NUnit user I run into a dead end with the error condition

![image](https://cloud.githubusercontent.com/assets/175113/18998733/b29ea9d4-86ee-11e6-8143-2a226201ed6b.png)

**Comment by jlewin** [comment]
Please feel free to close this bug if it doesn't seem relevant or helpful. I filed to give you some insight into the complications the current behavior causes due to a lack of details around the non-V3 error.

After spending the bulk of the morning looking into this problem it seems the most likely cause is our use of NUnit.ApplicationDomain, which I thought was V3 compatible but now need to investigate. It now seems plausible that the GetDriver implementation is looking at tests marked with the RunInApplicationDomain attribute and finding some aspect that turns on the V2 driver.

**Comment by CharliePoole** [comment]
Of course, there could be some error we don't know about, but on the surface it looks as if your test. references nunit 2. That's what leads us to use the nunit2 driver.

There are no "fallback warnings" because it's not really a fallback. The engine is looking at the available drivers to see which one can run your tests. The NUnit 3 driver has no special standing.

Every driver has its own rules. For the nunit 2 driver it's "assembly references nunit.framework assembly with major version 2."

**Comment by CharliePoole** [comment]
There us no NUnit RunInApplicationDomain attribute. Is this a locally modified build of NUnit?

**Comment by jlewin** [comment]
Sorry I wasn't more clear; nunit.applicationdomain is an external NUnit plugin:

- https://bitbucket.org/zastrowm/nunit.applicationdomain/
- https://www.nuget.org/packages/NUnit.ApplicationDomain/

We're using NUnit.ApplicationDomain 8.0 which has NUnit 3 as its only dependency. In my code, all NuGet and assembly references point at NUnit 3.

I'm hoping to find time tonight to walk through the driver selection code to better understand how the V2 driver selection occurs

**Comment by CharliePoole** [comment]
The driver selection code is (at least intended to be) dead simple! We examine the test assembly, looking for a reference to a framework. The first reference found that matches one of our drivers causes that driver to be used. Note that this implies an underlying assumption that you don't reference more than one framework. In the case of NUnit 2 and 3, however, it's only possible to reference one of them because the assemlies are both named `nunit.framework`.

The best way to deternime what you are referencing is to actually examine the test assembly using ildasm.exe. Everything you are doing in the source code is intended to affect what is referenced, but actually seeing the built assembly is the real proof that you have succeeded.

**Comment by CharliePoole** [comment]
FYI, the code that selectes the driver is here: https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/Services/DriverService.cs#L52

**Comment by jlewin** [comment]
>The driver selection code is (at least intended to be) dead simple! We examine the test assembly, looking for a reference to a framework

Dead simple sounds perfect. After a closer review our compiled assembly actually references NUnit 2.6.4. This is not what Visual Studio shows when the NUnit dependency is selected but definitely is what  gets compiled into the assembly.

I'll dig into the underlying test project to sort out why we're getting the old references. We recently migrated to v3 and apparently some level of that migration left the old references in place.

Thanks for clarifying the problem. I wish there had more detail in the test output that indicated the assembly under test had actual bindings to v2.6.4 to point out the flaws in our test project and to provide the same clarity you have.

**Comment by CharliePoole** [comment]
The problem here regarding more detailed information is that nunit doesn't see a problem to report. It's perfectly normal to run v2 tests, except it's not what you intended to do. Of course, nunit doesn't know your intent.

**Comment by jlewin** [comment]
True. I still wish it had said that my assembly was compiled against NUnit2 as the reason for it selecting the V2 driver as I would have scoffed but probably discovered the problem on my own. However, it did explained that it couldn't run my filter because I didn't have a V3 test and ultimately I just couldn't figure out how that was possible. 

The problem is now resolved. After clearing all bin/obj/NuGet caches and removing and readding NUnit on the offending project, it now runs without error and filters by class as originally intended. 

Thanks again for guiding me to the problem. Since it sounds like changes to the notification aren't of interest, it seems like this issue is closed.

**Comment by CharliePoole** [comment]
Do you have a specific change you might suggest for the message?

**Comment by jlewin** [comment]
I experienced confusion and frustration with the error suggesting I had non-V3 tests as my project only had v3 bindings. While investigating I was unable to find clarity regarding v2 versus v3 driver; --verbose didn't expose the problem and there was no --analyze or similar that might have cleared up the confusion.

If --verbose had output something like the table below, I would have been extremely confused but it might have sent me down the right track and would have exposed the truth and flaws of my configuration:
![image](https://cloud.githubusercontent.com/assets/175113/19015281/1cd68c5a-87b6-11e6-9673-1a2e1821819b.png)

Further, depicting this info in the verbose output would reveal how driver selection functions and change difficult troubleshooting from "what does ildasm say" to, "what does --verbose say" regarding your assemblies under test.

I doubt that the change is warranted but that's what I'd envision as an improvement

**Comment by CharliePoole** [comment]
If we were to do that, a number of changes would be required...

1. It could not appear at the start of the run, before NUnit has even looked at the tests. It could be an optional report, triggered by a command-line option - i.e. assembly summary report.
2. We would have to include the name as well as the version of the framework, since it might not be the nunit framework at all.
3. The info would have to come out of the XML file, which means we would have to put it there first.
4. The report could also include tests passed, failed etc. by assembly

Most likely we would want such a report to be an engine extension.

On the simplest level, the list of test files is displayed before the tests are even loaded, so the information is not available at that point. But let's imagine that we put it at the end, instead. That would mean that the name and version of the framework and the test driver used would have to be passed

**Comment by jlewin** [comment]
Sounds like a lot of work with very little demand

**Comment by CharliePoole** [comment]
For the NUnit team, I'd say that's true. For somebody who really needed the feature and wanted to develop the extension, I'd call it a maybe. 😄 

Since your problem is resolved and we aren't doing any changes here, I'll close this issue.
