### ISSUE TITLE
Could not load file or assembly "nunit.engine.dll" in my custom nunit runner

### ISSUE THREAD

**Issue by nachiappannk** [nunit/nunit-console#659]
Hi,

I am building my custom NUnit runner.
In my runner project I have added reference to "nunit.engine.api" and not to "nunit.engine"
I have done based on the hint at 
https://www.nuget.org/packages/NUnit.Engine.Api/

The hint said "This package includes the nunit.engine.api, which is normally the only assembly referenced by runners as well as by engine extensions. It is not intended for direct use by users who simply want to run tests using NUnit."

When I run the tests using by custom runner. I get an exception saying 
Could not load file or assembly "nunit.engine.dll"

However when I reference nunit.engine.dll in my runner, it works. No exception is thrown.

************************************
1. Should I reference NUnit.Engine in my custom runner or it's sufficient I reference only NUnit.Engine.API?

2. Is there any compatability documentation for NUnit.Engine, NUnit.Engine.API and NUnit?

**Comment by CharliePoole** [comment]
You don't need a reference but the engine needs to be present so that the API assembly can actually find it. Two approaches:

1. Copy the engine to output in a post-build event.
2. Reference it so that VS will copy it.

If you select (2) you should make sure that you never actually use anything in the engine, only work through the interfaces in the API. That way, you will be protected from future changes in the engine.

I'm not sure exactly what you mean by "compatibility documentation."

**Comment by nachiappannk** [comment]
Thank you Charlie. Makes perfect sense. 
I am making a nuget package out of my project, so I will choose option 2.

Regarding comparability documentation.
Is there some specific version of NUnit library that I

**Comment by CharliePoole** [comment]
Any version of the engine and API should work with all past versions of the NUnit 3 framework and will likely work with future versions.

The API and engine you bundle should match one another.

**Comment by nachiappannk** [comment]
Thank you Charlie... Your response gave me the confidence that I needed
