### ISSUE TITLE
Update text of NUnit.ConsoleRunner NuGet package

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#67]
Even though we state that it contains no extensions, many users install `NUnit.ConsoleRunner` and then report issues like TeamCity or NUnit 2 does not work. Users either do not read to the second paragraph, or they don't understand exactly what it means. We cannot just assume that users who only follow NUnit casually know what extensions are and what functionality they provide.

The current text is,

>This package includes the nunit3-console runner and test engine for version 3.0 of the NUnit unit-testing framework.

>Any extensions, if needed, must be installed as separate packages.

I think we should start off by saying that this is likely not the package many users will want, that they likely want `NUnit.Console`, then explain what this package provides. 

Any other ideas on how we can improve this?

**Comment by CharliePoole** [comment]
I'd want us to be careful about assuming we know what most users want and I'd prefer to educate them about extensions rather than try to make that knowledge unnecessary.

In the particular case of teamcity, I'm hoping we can eventually remove it from the NUnit.Console package.

In retrospect, our packages are badly named. Perhaps we should think about that as well.

**Comment by aateeque** [comment]
My finger in the air guess is the 80% use case is people wanting nunit.console.exe and most users would not benefit from knowing the intricacies of the different extensions and how they go together. The painstaking work that we had to undergo earlier in the week to find out about the missing packages wasn't a useful exercise and did not even result in us finding NUnit.Console package in the end. We just manually ended up adding a bunch of packages which made things work in teamcity.

I think the aggregate package, Nunit.console.nupkg, could be renamed to nunit.commandline and the description state clearly that if you are looking for the command line this package will get you all the dependencies you probably need for your TC build pipeline.

**Comment by CharliePoole** [comment]
@aateeque There will always be extensions that do important things for some users, so it seems like a good idea to call attention to the fast that they exist and which you are getting. It's especially important if we expect to change the set of extensions we bundle.

A new name could help but I find NUnit.Commandline confusing because it contains much more than one needs to run NUnit from the command-line.

Nobody who is not a teamcity user benefits from the TV extension and we made it into an extension so we could stop supporting it directly.

Nobody who has completely converted to NUnit 3 needs the V2 framework driver.

Similar statements can be made about every extension.

So I think we have to focus on making extensions inseparable to users, something we really haven't done up to now.

**Comment by CharliePoole** [comment]
@aateeque There will always be extensions that do important things for some users, so it seems like a good idea to call attention to the fast that they exist and which you are getting. It's especially important if we expect to change the set of extensions we bundle.

A new name could help but I find NUnit.Commandline confusing because it contains much more than one needs to run NUnit from the command-line.

Nobody who is not a teamcity user benefits from the TV extension and we made it into an extension so we could stop supporting it directly.

Nobody who has completely converted to NUnit 3 needs the V2 framework driver.

Similar statements can be made about every extension.

So I think we have to focus on making extensions inseparable to users, something we really haven't done up to now.

**Comment by CharliePoole** [comment]
@aateeque There will always be extensions that do important things for some users, so it seems like a good idea to call attention to the fast that they exist and which you are getting. It's especially important if we expect to change the set of extensions we bundle.

A new name could help but I find NUnit.Commandline confusing because it contains much more than one needs to run NUnit from the command-line.

Nobody who is not a teamcity user benefits from the TV extension and we made it into an extension so we could stop supporting it directly.

Nobody who has completely converted to NUnit 3 needs the V2 framework driver.

Similar statements can be made about every extension.

So I think we have to focus on making extensions inseparable to users, something we really haven't done up to now.

**Comment by aateeque** [comment]
@CharliePoole agreed, it's useful to point out the extensions. How about names like NUnit.Console.TeamCity - which would be an aggregate of extensions you need for console runner in TC?

**Comment by CharliePoole** [comment]
It's a thought. If not us, Jetbrains could publish it.

**Comment by ChrisMaddock** [comment]
Based on: 
- The majority of our users will want a default configuration that 'just works' - downloading a couple of extra unused packages isn't a concern
- Having packages named `NUnit.Runners`, `NUnit.Console` and `NUnit.ConsoleRunner` _IS_ a little confusing.

Why don't we rename the 'single-component' packages as `NUnit.Component.*`? (i.e. `NUnit.Component.ConsoleRunner`, `NUnit.Component.Engine`, `NUnit.Component.EngineApi`)

So:
- The casual user finds a single package named `NUnit.Console` - which contains all default functionality with the common extensions, and 'just works'.
- Those doing 'more advanced' set-ups, should have an understanding of the structure, and can use the 'less discoverable' `NUnit.Component.*` and `NUnit.Extension.*` packages, and build the minimal structure they require.

I agree there's a problem, but I'm not sure we can do much more with the package description than we already do. Renaming packages isn't ideal - but I'm not sure we've got it quite right yet. Naming things is hard!

**Comment by CharliePoole** [comment]
I'd rather not get into the "component" description because it seems to mean a piece of software that doesn't stand on it's own. But that's not the case of any of our packages except possibly for NUnit.Engine.Api, which is pretty clearly designated as being for developers of runners and extensions. I think all he engine-related packages are clearly indicated as not at all being for normal users, but we could review the wording for the next release.

So let's limit the discussion, for the moment, to extensions.

In my view, our NUnit.Console package with five extensions is __not__ actually what "most people" need. Most people need NUnit.ConsoleRunner. The combined package really only exists because of history: each of the five was once part of the engine before we made them into a separate package, with the notion - for me at least - that most people won't be getting them in the future.

If our separation includes anything we __really__ believe most people need, maybe we should back that package out and keep it bundled.

**Comment by aateeque** [comment]
> If our separation includes anything we really believe most people need, maybe we should back that package out and keep it bundled.

Think packages should be smaller as that leads to greater flexibility in their development. Smaller packages can group together into aggregate packages that serve a purpose together; eg. `System.Reactive`.

**Comment by CharliePoole** [comment]
@aateeque I think I wasn't clear enough there, because I was assuming some context.

The various extensions have always been separate packages and will stay that way. More recently, we decided to develop and release those packages on a separate schedule from NUnit itself. That's the decision we could conceivably reverse - not the existence of the packages but the degree to which they are maintained separately. Hope that makes sense.

**Comment by rprouse** [comment]
I would prefer not to rename packages. I think if we do that then the existing packages will live on in NuGet further polluting the waters and confusing users. We already have two identical packages `NUnit.Console` and `NUnit.Runners` :frowning: 

Is there any appetite to deprecating the lesser used `NUnit.Console` in favor of `NUnit.Runners`? We could release the 3.5 `NUnit.Runners` switching the title to **NUnit Console Runner With Extensions** and not release a new version of `NUnit.Console`, but go into NuGet and switch the title to **NUnit Console - Deprecated use NUnit.Runners**

I agree with Charlie that we should educate users about extensions, that was my intention of this issue. I want to use NuGet as part of that education. Maybe switch the title of `NUnit.ConsoleRunner` to **NUnit Console and Engine** and then switch the description to,

>This package includes the nunit3-console runner and test engine for version 3.0 of the NUnit test framework.
>This package does not include the extensions that add functionality like running NUnit 2.x tests, outputting NUnit 2 test results or running under TeamCity. Those extensions, if needed, must be installed as separate packages.

I also think we should update our documentation with a better explanation of the various packages and their uses.

**Comment by CharliePoole** [comment]
@rprouse I don't think we should deprecate NUnit.Console. NUnit.Console. We already deprecated the older NUnit.Runners in favor of NUnit.Console. The history is that NUnit.Runners, under V2, included the Gui. I created NUnit.Console to give the batch function without the implication that the Gui was included in it.

Reading your comment, I wondered why the deprecated one is still the one that's used more, so I looked at nuget.org. The reason seems to be in the titles:

| Package | Title |
|----------|------|
| NUnit.Console | NUnit Console Runner Version 3 With Extensions ||
| NUnit.Runners | NUnit Console Version 3 |
| NUnit.ConsoleRunner | NUnit Console Runner Version 3 (no extensions) |

In a listing of available packages, you only see the titles and a line or two of description so we need to put the important information there, rather than later.

I'd redo the titles as follows:

| Package | Title |
|----------|------|
| NUnit.Console | NUnit Console Runner Version 3 Plus Extensions ||
| NUnit.Runners | NUnit Console Runner - Deprecated use NUnit.Console |
| NUnit.ConsoleRunner | NUnit Console Runner Version 3 (no extensions) |

Charlie

**Comment by rprouse** [comment]
I'm okay with that. I think that the reason that the deprecated version has more downloads has more to do with people upgrading existing projects and with the fact that NUnit.Runners has so many downloads that it shows up much higher in the search.

NUnit is currently the third package listed when you add new NuGet packages and NUnit.Runners shows up on the first page at tenth place. NUnit.Console is way down in 78th place, so most users don't see it unless they search specifically for it.

If we deprecate NUnit.Runners, then we should add that text to the description (or summary?) since that is what shows up in Visual Studio, not the title from NuGet.org.

![image](https://cloud.githubusercontent.com/assets/493828/19024821/c57d7e20-88da-11e6-9088-ed142d492065.png)

**Comment by CharliePoole** [comment]
Good point. Some people only see it in VS - probably most people.

**Comment by CharliePoole** [comment]
If you look at the nuget.org site, you see the title and description from the nuspec file. If you look on VS you see the ID and the summary!

Therefore, I'll supplement the above title changes with the following summary changes:

| Package | Summary |
|-------------|-------------|
| NUnit.Console | Console runner for version 3 of the NUnit unit-testing framework with selected extensions. |
| NUnit.Runners | Deprecated NUnit 3 Console Runner - Use NUnit.Console or NUnit.ConsoleRunner. |
| NUnit.ConsoleRunner | Console runner for version 3 of the NUnit unit-testing framework, without any extensions. |

One question @rprouse: Should we use "Deprecated" or "Obsolete" ?
