### ISSUE TITLE
Xml attributes "type" are only ="TestSuite" in --explore file when using --where or --testlist.

### ISSUE THREAD

**Issue by justsomeuselessguy** [nunit/nunit-console#682]
Xml attributes "type" are only ="TestSuite" in --explore file when using --where or --testlist. But when --where or --testlist are not used there is other types like "ParameterizedMethod" for example. Is this a bug?

**Comment by CharliePoole** [comment]
This is actually created by the framework, but easy enought to answer here. :smile: 

The `type` attribute is used to distinguish different types of test suites, which is why it only appears on the `test-suite` element. There are many such types, including `Project`, `Assembly`, `TestSuite`, `ParameterizedMethod`, etc. You can see all the types available if you explore or run all the tests in your test assembly.

If you use a filter, then what you get will depend on the content of the filter. That's not an error, it's just that you are restricting what is output.

However, if you saw the __same__ test displayed differently with and without a filter, that would be an error, so please let us know.

**Comment by justsomeuselessguy** [comment]
I have following situation.
For example test-suite with fullname="NUnit.Framework.Internal.AssemblyHelperTests.GetAssemblyPathFromCodeBase" has type="ParameterizedMethod" when running Nunit.framework.tests.dll without filters, but when I use --where=namespace=~NUnit.Framework.Internal - the same test-suite has type="TestSuite" in explore file.

**Comment by justsomeuselessguy** [comment]
[example.zip](https://github.com/nunit/nunit-console/files/3625994/example.zip)

**Comment by mikkelbu** [comment]
Hi @justsomeuselessguy 
This sounds very closely related to nunit/nunit#3171 that was solved in NUnit 3.12. Which version of NUnit (and NUnit-Console) are you using?

**Comment by justsomeuselessguy** [comment]
Hi @mikkelbu 
I'm using NUnit Console Runner 3.9.0

**Comment by mikkelbu** [comment]
And which version of NUnit? As something similar was solved in NUnit 3.12.

**Comment by justsomeuselessguy** [comment]
Do I need binding redirect to use NUnit Console Runner 3.10.0 with NUnit 3.12, or there is an another way?

**Comment by CharliePoole** [comment]
@justsomeuselessguy They are completely independent products. The console runner has no dependency on the framework. If possible, it's best to use the latest version of each one.

**Comment by CharliePoole** [comment]
Another check you could make: execute the tests with and without a filter. If the XML looks correct when running but not when using explore, then it's probably the issue that @mikkelbu mentioned.

**Comment by justsomeuselessguy** [comment]
> XML looks correct when running but not when using explore

That is correct. So will it be fixed in further versions of console runner?

**Comment by justsomeuselessguy** [comment]
> And which version of NUnit? As something similar was solved in NUnit 3.12.

The problem is that I need to use exactly NUnit Console Runner. I can't use NUnit 3.12.

**Comment by mikkelbu** [comment]
@justsomeuselessguy as @CharliePoole says the two products are orthogonal. You can refer to Nunit (the attributes, asserts, etc) from your tests and the using the Console to execute the tests. And it is the NUnit you need to update and not the Console.

**Comment by justsomeuselessguy** [comment]
Sorry, now I get what your'e saying. It works that way, thanks.
