### ISSUE TITLE
Allow custom framework drivers to run before NUnit3DriverFactory

### ISSUE THREAD

**Issue by Sebazzz** [nunit/nunit-console#70]
As per [docs](https://github.com/nunit/docs/wiki/Framework-Drivers) it is possible to implement framework drivers. I'd like to execute some code before and after the `NUnit3DriverFactory` runs. 

I would do this by wrapping `NUnit3DriverFactory` in my own `IDriverFactory` implementation, but it just happens that the default driver factory [is always queried](https://github.com/nunit/nunit-console/blob/81aebbac6bc299d53a48d09c301dde5fae7349a5/src/NUnitEngine/nunit.engine/Services/DriverService.cs#L101) first.

I would like to propose that the NUnit3DriverFactory is queried *after* the extensions have been queried, this would allow better extensibility when it comes to running NUnit 3 test assemblies.

**Comment by CharliePoole** [comment]
We could certainly put the internal NUnit3DriverFactory at the end of the list of factories, or query it last in some other case. That would allow someone to write their own replacement driver. When I set this up I gave that a little thought but concluded that we probably didn't __want__ people to do that! Imagine the bug reports: "My implementation is just like yours except for one thing but this other thing stopped working." 😄 

OTOH, if you have a valid use for replacing the driver, I'd like to hear it. Maybe the initial decision was too hasty.

OT3rdH, if you really just want to run some initialization code, rather than replacing the driver, perhaps we can figure out another way to let you do it.

**Comment by Sebazzz** [comment]
In my case I wanted to replace an internal implementation of an interface used in the FrameworkController, a means to an end of extending the way test filters are executed.

> When I set this up I gave that a little thought but concluded that we probably didn't want people to do that! Imagine the bug reports: "My implementation is just like yours except for one thing but this other thing stopped working." 

I understand that. Still, if you're giving people them means to extend the engine, you're also given them all the power to blow the framework up.

**Comment by CharliePoole** [comment]
Fair enough.... Maybe the answer is to give more visibility to what driver is being used for each assembly. That way, we would immediately know the problem is with CustomNUnit3FrameworkDriver and not our NUnit3FrameworkDriver.

Could you say more about what you want to implement? We already have a backlog issue to allow extensions to extensions. It may be that you would be better served by extending the NUnit 3 framework driver as opposed to replacing it.

If that  turns out not to be the case, I'd be happy with the original request plus some better visibility of the fact that we are using a custom driver.

**Comment by Sebazzz** [comment]
> Could you say more about what you want to implement?
I want to use my own implementation of `ITestFilter`, in order to influence which tests are and are not executed given a selection of tests.

> It may be that you would be better served by extending the NUnit 3 framework driver as opposed to replacing it.
Yes, I suppose so.

**Comment by CharliePoole** [comment]
How would the filter be passed into the framework... I.e. how would a user specify it?

**Comment by Sebazzz** [comment]
A user would specify a `ITestFilterFactory` using an attribute: `TestFilterFactoryAttribute`.

Internally, the attribute would implement `IApplyToTest` and in the implementation set a property on the test passed in (the root fixture, so either an TestAssembly or SetUpFixture) to the `ITestFilterFactory` type specified. 

When `Run` is called on the FrameworkController, the `ITestFilterFactory` is instantiated, the appropiate method is called, and the resulting `ITestFilter` is passed into the framework just as it is now.

``` C#
interface ITestFilterFactory {
    ITestFilter CreateTestFilter(string specification);
}
```

**Comment by CharliePoole** [comment]
So the "user interface" would merely be an assembly- or fixture-level attribute in the test code? What happens to the filter that is passed into the framework?

**Comment by Sebazzz** [comment]
> So the "user interface" would merely be an assembly- or fixture-level attribute in the test code?

Yes. Not it is meant for extending the framework, especially using external libraries. Not for your average user who wouldn't do it himself.

> What happens to the filter that is passed into the framework?

It would just run as it runs now. If you meant the "current filter" as it is implemented now, well, it can be created and called from the custom filter.

**Comment by CharliePoole** [comment]
I got us off into a side discussion of filters. It would be cool to have a hook that allowed defining custom filters, but the original topic here was order of selecting framework drivers.

I think that your request is reasonable so long as we add to the XML some info about the driver being used. That way, runners can display it where appropriate.

**Comment by Sebazzz** [comment]
Thanks!
