### ISSUE TITLE
Transform option does not work on Mac

### ISSUE THREAD

**Issue by jpc1963** [nunit/nunit-console#711]
I have written NUnit tests for iOS / Android & windows apps. And I use **nunit3-console.exe** to run the tests. I would like to use the Transform option to create more readable output.
So I downloaded the transformation XSLT files from here: [](https://github.com/nunit/nunit-transforms)

On my mac I use the following command to run my tests: **mono nunit3-console.exe My.UITest.dll --test="UITest.Fixtures.InitialLogin(Synergy,iOS)" --result=test.result.txt;transform=text-summary.xslt**

The command ignores the transform option. If I run the same command on windows I see the test results transformed OK. Any ideas?

**Comment by mikkelbu** [comment]
@jpc1963 We will need more information to help you, especially two of items requested in the bug template
* Method of installation (e.g. NuGet, zip, msi)
* Version of the NUnit Engine/Console

Also it would be nice with the output from the console, as it seems we print the selected format to the output. 

Does it help to escape the parameter? e.g. `--result="test.result.txt;transform=text-summary.xslt"`

**Comment by jpc1963** [comment]
Oops, I forgot all about the version information. I am using:
Console-runner: 3.10.0
Xamarin.UITest: 3.0.3
Nunit: 3.12.0
Installed via nuget into my Xamarin test project.

BUT: escaping the parameter works OK. So this works: **--result="test.result.txt;transform=text-summary.xslt"**

So problem solved. Thanks.

**Comment by mikkelbu** [comment]
Great. So I don't think this is something special about Mac. I had a related problem with PowerShell, so it is mostly how the commandline escapes arguments.

**Comment by ChrisMaddock** [comment]
I agree with Mikkel, but wouldn't have spotted that. Good thinking! 😄

**Comment by jscott-concord** [comment]
Also did not work using 3.11.1 on windows 10 without adding quotes

**DOES NOT WORK:** -result=myfile.html;transform=html-report.xslt
**WORKS:** -result="myfile.html;transform=html-report.xslt"

Results (nunit3) saved as sample.html
transform=text-report.xslt : The term 'transform=text-report.xslt' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:62
+ ... xe .\IWSTestSuite.dll --result=sample.html;transform=text-report.xslt
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (transform=text-report.xslt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by CharliePoole** [comment]
Up to now, NUnit has never provided info about how to escape parameters to work on the command-line for various operating systems. The rationale was that  this is not knowledge about NUnit but about how to use a particular command-line. There may also have been, at least in the past, a feeling that "everybody knows that" since NUnit was developed at a time when most developers spent a lot of time at the command-line.

Has that changed? Should we have a page somewhere that tells how to enter parameters on the command-line? It would probably have to cover Windows, Linux and Mac, the last one being a bit of a problem for some of us. :smile: 

Alternatively, could we have a page with links to appropriate external information for each OS?
