### ISSUE TITLE
Deprecate deprecated packages on nuget.org

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#720]
https://docs.microsoft.com/nuget/nuget-org/deprecate-packages

Nuget.org's package deprecation functionality is now available. 😄 We should make use of it for our two deprecated packages.

**Comment by ChrisMaddock** [comment]
The nunit-console-with-extensions Choco package needs to be added to the list for removal from the repo, it catches me out every time. 🙁

**Comment by CharliePoole** [comment]
Two packages are deprecated and Chris added a third package, which he recommended we deprecate. Currently deprecated packages use the convention-based approach of indicating they are deprecated in the title and having a dependency on the replacement package where there is one.

Currently, we are re-publishing the deprecated packages, using a new version number, every time we publish. I don't think this makes sense, because the whole idea is that we don't want to keep maintaining these packages. @nunit/engine-team What do you think? Am I missing some reason why this is useful?

## Packages

Details follow on each of the three packages. They are all packages for nuget.org unless otherwise stated.

### nunit.engine.netstandard

This is an old alternative engine, which we no longer use. The NUnit.Engine package replaces it. We currently release this with an new version number every time we publish packages.

__Actions:__ Stop Publishing; Convert to NuGet Deprecation Feature (?)

### NUnit.Runners

This is an old naming for the current NUnit.Console package, which includes both NUnit.Console.Runner and our five standard extensions.  We currently release this with an new version number every time we publish packages.

__Actions:__ Stop Publishing; Convert to NuGet Deprecation Feature (?); Update Description

### nunit-console-with-extensions (Chocolatey package)

This is an old package with no exact equivalent. In the Chocolatey environment, bundling extensions doesn't make a lot of sense because it's so trivial to add extensions from the command line. This package was added in error and we don't have any precise equivalent - users should install nunit-console-runner plus whichever extensions they want.

__Actions:__ Stop Publishing; Deprecate on Chocolatey.org; Update Description

## Explanation of Actions

### Stop Publishing

We would remove the publication of the deprecated packages from the build script. The `nuspec` files would be kept and moved to a special folder in case a modified version needs to be pushed in the future. We would add instructions about how to push them manually in that case.

### Convert to NuGet Deprecation Feature

Although this is basically the main point of the issue, I have marked this action with a question mark in each case.

@nunit/engine-team What advantage do you see in this conversion, as applied to packages we have already deprecated in the convention-based way.

### Deprecate on Chocolatey.org

Chocolatey has its own approach to convention-based deprecation. AFAIK the new NuGet deprecation feature isn't available.

### Update Description

Some descriptions list features, which may or may not be present in the replacement package. The description needs to be more generic. Example: NUnit.Runners lists the extensions which are included, even though that may change in the NUnit.Console package at some future time.

@nunit/core-team Hoping for your input on all of this before doing it!

**Comment by jnm2** [comment]
I support all of these actions (they don't look mutually exclusive). Advantages to using nuget.org deprecation are that tooling understands it (both CLI and warning icons in Visual Studio NuGet Package Manager) and it presents nice UI online where it links to the recommended replacement package.

**Comment by CharliePoole** [comment]
Thanks @jnm2 

I intended the lists of actions to all done completely... e.g. Stop Publishing AND Convert AND Update. There's a separate list for each extension because each one needs slightly different things.

I guess once I do one of them, we'll get to see what the UI looks like and we can change it for the others. I think `nunit.engine.netstandard` requires the least, so I'll do it first.

**Comment by CharliePoole** [comment]
I updated the description to clarify the action steps and added checkboxes.

**Comment by CharliePoole** [comment]
I've done a PR for the part of this that removes the deprecated packages from our regular build process. More work is needed to change __how__ we deprecate them, but that does not have to be done in conjunction with the release.

**Comment by CharliePoole** [comment]
@nunit/engine-team This is partly done as planned and I don't intend to do any further work so I'm closing it. Let me know if you see any problem with this.
