### ISSUE TITLE
Video of test run using DataCollection

### ISSUE THREAD

**Issue by santhosh-James** [nunit/nunit-console#722]
Is it possible to use DataCollector to generate video of the tests? i am using dotnet test to run the tets

DataCollector uri="datacollector://microsoft/VideoRecorder/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder.VideoRecorderDataCollector, Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Screen and Voice Recorder">
        
        <Configuration>
          
          <MediaRecorder sendRecordedMediaForPassedTestCase="true"  xmlns="">           
            <ScreenCaptureVideo bitRate="512" frameRate="2" quality="20" />
          </MediaRecorder>
        </Configuration>
      </DataCollector>

**Comment by ChrisMaddock** [comment]
Hi @santhosh-James,

I've had a quick Google - I think the problem you have here is really with dotnet test and the DataCollector API, rather than anything related to NUnit.

Suggest you approach the vstest guys for help here instead - but perhaps this thread will help: https://github.com/Microsoft/vstest/issues/1959 or maybe the docs here: https://docs.microsoft.com/en-gb/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017#video-data-collector

Good luck!
