### ISSUE TITLE
Console runner not using registered ITestEventListener extension (dotnet test does)

### ISSUE THREAD

**Issue by replaysMike** [nunit/nunit-console#736]
Hey guys.

I wrote an extension for NUnit I'd like to publish soon but I noticed the nunit-console isn't running the configured extension. However, when I run `dotnet test` or within Visual Studio it does execute.

```csharp
[Extension(Description = "Provides Test event monitoring and logging", EngineVersion = "3.4")]
public class TestMonitorExtension : ITestEventListener, IDisposable {}
```
To enable the extension, I've included a file in my extension called `NUnit.Extension.TestMonitor.addins` which is copied to the build output and contains:

```
NUnit.Extension.TestMonitor.dll                   # Include the TestMonitor nUnit extension
```

This works fine, I confirmed that it runs via file logging. I just don't know why the console runner doesn't pick up the extension. I tested this by building a sample test that multi-targets .net core and .net 4.8, and am running the console runner on the net 4.8 dll (I'm aware no .net core support). I've also tried registering manually with a regular `.addins` file but same result.

Full output showing the test is running and passes, but no log file was created by my extension in this case:

```
NUnit Console Runner 3.11.0 (.NET 2.0)
Copyright (c) 2020 Charlie Poole, Rob Prouse
Tuesday, February 11, 2020 5:57:57 PM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    .\NUnit.Extension.TestMonitor.Tests\bin\Debug\net48\NUnit.Extension.TestMonitor.Tests.dll

Running Should_Work

Run Settings
    DisposeRunners: True
    WorkDirectory: C:\gitrepo\personalcode\NUnit.Extension.TestMonitor\NUnit.Extension.TestMonitor
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.8
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    RuntimeFramework: net-4.0
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-02-12 01:57:57Z
    End time: 2020-02-12 01:57:58Z
    Duration: 0.948 seconds

Results (nunit3) saved as TestResult.xml
```

**Comment by CharliePoole** [comment]
Use the console --list-extensions option to confirm that your extension is not installed.

For the `.addins` file you listed to work...
 * It would have to be located in the same directory as the copy of the engine being used by the console runner.
 * The extension itself would have to be located in the same directory.

If that's not the case, please tell us more about your installation, especially the relative location of the engine WRT the tests you are running.

**Comment by replaysMike** [comment]
I see, I wasn't aware the `.addins` file and extension had to be with the console runner, I thought it had to be in my test project build folder that is being run. The docs aren't really clear on this, and that seemed to partially work (at least for `dotnet test`)

**Comment by CharliePoole** [comment]
Technically, with the engine, but that's also where the console runner is.

In fact, the need for "stuff" to be in the output folder is a "feature" of .NET Core. The nunit adapter has to be there, which means the engine is there as well, so that's where the `.addins` files go.

Generally, the various nunit packages (nuget, msi, adapter, etc.) come with individual `.addins` files with different content. For example, if you install the console runner from nuget.org, you will get a particualar `.addins`  file. If you install it via chocolatey, you get a different one. Those files are set up, using wildcards, so that the chocolatey package (for example) finds any extensions installed via chocolatey, but not otherwise. Same for nuget.

So, it's not surprising that you may need to have a different `.addins` file for each environment, although I agree it's a pain. There's a separate issue suggesting alternative ways, such as an environment variable, to point to additional addins files.

BTW if you are building for both framework and core, you should know (if you don't already) that referenced assemblies don't get copied to output automatically under .NET Core. It knows how to find them without copying in most cases, but not in dynamic loading situations such as this.

**Comment by replaysMike** [comment]
Gotcha thanks Charlie. I was able to get it working for both the NUnit console runner and dotnet test by combining two strategies. 

For the NUnit console I:
* manually edit the `nunit.bundle.addins` for the nunit-console and add my extension which is placed in the `./addins/mycustomextension` folder
* I can resolve my extension configuration for .net framework in the above folder as well

For `dotnet test`:
* I include a file with my extension that gets copied to the build folder (ending up in each test) called `MyExtension.dll.addins` which contains the same addin configuration. NUnit engine picks this up and it works for both .net framework and .net core (and I can load my extension configuration for each specified in the test assembly)

Took a day to figure out, but this is working well. I'll make sure to document this clearly in my extension ([NUnit.Extension.TestMonitor](https://github.com/replaysMike/NUnit.Extension.TestMonitor))

**Comment by CharliePoole** [comment]
Glad to hear that! BTW, in case it isn't obvious, in any folder where `.addins` files are looked for, you can have multiple such files. This is so specific extensions can provide their own file rather than having to edit some central file.
