### ISSUE TITLE
Question - How To Use ResultReporter in ConsoleRunner RunTests

### ISSUE THREAD

**Issue by JoeConroy93** [nunit/nunit-console#744]
Hi All,

I Am utilizing the NUnit.Engine class within c# web app to explore and execute test cases in Nunit.
i am currently using the following code within a method 

```
        public IHttpActionResult PostTests(string DLL, string TestCommand)
        {
            ITestEngine engine = TestEngineActivator.CreateInstance();

            try
            {
                TestPackage package = new TestPackage(PaymentsDLL);
                ITestRunner runner = engine.GetRunner(package);

                TestFilterBuilder builder = new TestFilterBuilder();
                builder.SelectWhere(TestCommand);

                TestFilter Myfilter = builder.GetFilter();
                XmlNode result = runner.Run(null, Myfilter);

                engine.Dispose();
                runner.Dispose();

                return Ok(result);
            }
            catch (Exception ex)
            {
                engine.Dispose();
                return BadRequest(ex.Message);
            }`
```

this is working fine to execute the selected tests and to return the XML information about the runs, however the format of this output does not seem to be the same as the XML output generated by the Console or the GUI when ran independently (it will not work within the Pickles Living doc Suite)

I am wondering how i can get the output to mirror that given by the console or GUI; i can see within the ConsoleRunner class that there is some code but i am unsure how i can use or trigger this method. (sorry i have not been a developer for very long!)

````
if (result != null) 
           { 
               var reporter = new ResultReporter(result, writer, _options); 
               reporter.ReportResults(); 

 
                foreach (var spec in _options.ResultOutputSpecifications)                { 
                   var outputPath = Path.Combine(_workDirectory, spec.OutputPath); 
                   GetResultWriter(spec).WriteResultFile(result, outputPath); 
                  writer.WriteLine("Results ({0}) saved as {1}", spec.Format, spec.OutputPath); 
            } 
}
```
 
 
any support would be greatly appreciated ! - really happy with the NUnit Framework /Packages :)

Thanks

**Comment by CharliePoole** [comment]
If I understand the documentation correctly, Pickles supports nunit3 test result format as well as the original V2 nunit format. You are getting results in the nunit3 format when you run the tests. You could simply just write that output to a file yourself or you could use a ResultWriter. The ResultWriter for nunit3 format does nothing special - it just writes it all to a file, as can be sene here: https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/Services/ResultWriters/NUnit3XmlResultWriter.cs#L51

You can either copy the code from the above link into your own code or you can ask the engine to give you the result writer like this...

```
var resultService = _engine.Services.GetService<IResultService>();
var resultWriter = resultService.GetResultWriter("nunit3", new object[0]);
writer.WriteResultFile(xmlNode, "filenameORpath");
```

If it turns out that Pickles really prefers the old "nunit" format, then you will need to install the engine extension for that format. That's slightly more complicated, so let me know if you need it.

**Comment by JoeConroy93** [comment]
Hi Charlie, 

thanks for your reply, yes - pickles supports all of the nunit results formats. I have written the contents of "XmlNode result" to a .xml document but it wasn't valid still. I used the above code and this worked! The output produced by the 'resultsWriter' was completely different than what i was getting from writing just the result node, i am wondering if this is were i went wrong? (by just writing the 'result' node to a file rather than the entire doc/content?)

Thanks anyhow - all working!

**Comment by CharliePoole** [comment]
Odd. It's the same XmlNode in either case, right? Possibly an error in how you serialized it or maybe you just wrote the top nice and not the nested nodes.

Glad it's working anyway.
