### ISSUE TITLE
Add teamcity-event-listener to NUnit-x.x.x.zip file

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#77]

**Comment by NikolayPianikov** [comment]
@rprouse @CharliePoole and team do you have any objections?

**Comment by CharliePoole** [comment]
I don't understand... hasn't it always been in the zip?

**Comment by NikolayPianikov** [comment]
Yes it was. But now it is not a part of console runner CI. So when I run a build to make a packages .zip does not contain this extension. Or we are planning to make a releases manually for a long time?

**Comment by CharliePoole** [comment]
OK, as we are moving the extensions to separate repos, they are being removed from the zip in nunit-console. The idea was that we would put them back "somewhere" but not necessarily where they currently are.

@ChrisMaddock Do you think we should do the zip in the nunit-distribution project? In the past it used the same image that was used by the msi.

Note that this is different from the NuGet meta-packages, because the zip contains an actual copy of the extension.

@NikolayPianikov I don't think we will be including TeamCity extension in the zip forever, since it is in the process of becoming JetBrains' extension, but I agree it should be there for this release.

@rprouse Any thoungs on this?

**Comment by rprouse** [comment]
I think for this release it would be nice to see the extensions in the ZIP. Since the installer package is already pulling things together, that would be the easiest place to produce the ZIP file. @ChrisMaddock do you think you could pull that together this weekend?

**Comment by ChrisMaddock** [comment]
Away this weekend I'm afraid, but will see if I can get something done tomorrow. 😄

**Comment by CharliePoole** [comment]
If you don't get it finished, I can continue.
