### ISSUE TITLE
TempResourceFile.Dispose causes run to hang

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#8]
@CharliePoole commented on [Tue Sep 29 2015](https://github.com/nunit/nunit/issues/848)

This Dispose method contains an infinite loop, exited via a break statement. Sometimes, when all other threads are also waiting, the exit requirements are never met.

Someone needs to examine the reasons behind the logic that is there and modify it so it doesn't hang.

---

@CharliePoole commented on [Tue Sep 29 2015](https://github.com/nunit/nunit/issues/848#issuecomment-144281039)

I've noticed that this is often a problem when running a non-parallelizable STA test. Makes sense.

**Comment by tom-dudley** [comment]
I can't wrap my head around why the loop would ever be infinite. It seems to me that `GetDirectoryPath` is guaranteed to either be null or empty once it hits the root node. I can only think that the function is somehow returning the path which was passed in, which is highly doubtful.

Why would a non-parallelizable STA test make this more likely?

**Comment by CharliePoole** [comment]
The comment about non-parallelizable STA tests relates to the original issue that was written against the framework. I suspected that the call to Delelete might not return. However, it's irrelevant now that we are talking about the engine tests.

There may no longer be an issue. The only thing that bothers me about that method right now is the use of the name `path` for two purposes. It takes some knowledge of C# syntax to understand which value is being used in a given statement.

I think I'd be ready to close this in any case.

**Comment by mikkelbu** [comment]
I just looked a bit into this issue, as and I cannot see how the code could hang. The only problem I can see is that sometimes the `Dispose` will not remove the file/folder due to an exception being thrown, or possibly leaving empty folders behind if other threads/processes have a delete share to the file making the `Delete` method return before actually deleting the file (see e.g. https://stackoverflow.com/questions/50295265/file-exists-returns-true-after-file-delete). 

@nunit/engine-team I propose to delete the class `TempResourceFile` since it is currently unused in the project.
