### ISSUE TITLE
Console runner not using registered ITestEventListener extension

### ISSUE THREAD

**Issue by NaZaRKIN123** [nunit/nunit-console#812]
Hi All,

I've tried to create my own extension to ITestEventListener, not for some reason console runner doesn't pick it up.
There is very little information on how to do it so I googled most of it on StackOverflow or other issues here, e.g.https://github.com/nunit/nunit-console/issues/736

Seems to me that I did everything: put it in the separate assembly, added .addins file, added correct attribute for the class of implemented method.

So when I run it from nunit3-console it doesn't print the text from TestEventListener.

Example code is here: https://github.com/NaZaRKIN123/TestMonitor

**Comment by CharliePoole** [comment]
Expanding on @mikkelbu's comments...

I've never used a nested type for an extension. All of our distributed extensions use top-level public classes for the extension points. So, it's not surprising that it doesn't work. It could be considered a bug if there's a good reason to use a nested type, but I don't see it as very important.

No part of the engine uses a reference to the NUnit framework or any other framework. The idea is that the engine is completely independent of frameworks that run under it. Extensions are fundamentally part of the engine so they should follow the same rules. For a simple test like this, you can use Console.WriteLine().

**Comment by NaZaRKIN123** [comment]
> The first thing I did was to follow the suggestion in #736 and place the .addins file in the correct folder

Can you share where that folder is? Isn't it just a Bin folder where the engine.dll got copied?

**Comment by ChrisMaddock** [comment]
I'm afraid that's not how engine extensions are designed - they're a "per-engine" tool rather than a "per project" one.

I'll close this issue now as I think the questions are answered - please feel free to comment further if there's more to clarify. 🙂

**Comment by CharliePoole** [comment]
@NaZaRKIN123 The usual way to do this is to have one engine per project through use of NuGet packages. If your project installs the console runner and engine as a tool through a nuget package reference, and also includes your extension as a nuget package reference, everything just works!

**Comment by NaZaRKIN123** [comment]
Sound reasonable. How should I put .addins file into the packages folder if it's generated?

So when I added packages and run the next command:
\TestMonitor\packages\NUnit.ConsoleRunner.3.11.1\tools> .\nunit3-console.exe ../../../Tests/bin/Debug/Tests.dll
I don't see the output from my extension.

What is missing?

**Comment by CharliePoole** [comment]
Are you saying your extension is now a nuget package? In your original example, it was in a folder in your project. Could you just post a simplified directory structure showing where the three main things are located WRT one another?

1.  NUnit  console and engine
2. Your extension
3. Your test assembly

I can only fingure out 1 and 3 from the above.

**Comment by CharliePoole** [comment]
Try this as a way to understand what's needed.

1. Install NUnit.ConsoleRunner from nuget.org in a test project.
2. Install NUnit.Extension.NUnitV2Driver the same way.

Examine how the two packages are installed in your tools directory. The addins file under the console runner has some relative paths in it which will find the extension directory. The extension directory itself contains an addins file, which points to the actual assembly to be loaded.

You can do the same thing either by (1) creating a nuget package for your own extension or (2) simulating the installation of the package by simply creating the directories yourself.

If your extension  is just a single assembly, you don't need an addins file in the directory that contains it. NUnitV2Driver uses one because it has some supplementary files that are referenced by it but do not get loaded by the engine. Without an addins file in the extension directory, the engine will try to use every assembly it finds, which is not a problem so long as they contain extensions or at least don't throw an exception.
