### ISSUE TITLE
Seemingly redundant dependency on Microsoft.DotNet.InternalAbstractions for platforms other than .Net Standard 1.6

### ISSUE THREAD

**Issue by Dmitry-Me** [nunit/nunit-console#818]
This line https://github.com/nunit/nunit-console/blob/0d037ca9d569282c14b798ed6a69b8532fc88a4e/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs#L451 makes the only use of anything from Microsoft.DotNet.InternalAbstractions in the entire codebase. This line only gets to the compiler when the package is compiled to target .Net Standard 1.6 because all other platforms have `Environment.Version` which is well known and is used almost everywhere.

However the .nuspec and .csproj files are crafted such that the dependency on Microsoft.DotNet.InternalAbstractions is not restricted to .Net Standard 1.6 Those files also list this dependency for .Net Standard 2.0 and .Net Core 3.1 

The problem is Microsoft.DotNet.InternalAbstractions is published in Nuget with no license specified which is is long known issue https://github.com/dotnet/sdk/issues/9889 This makes Microsoft.DotNet.InternalAbstractions formally "unlicensed" and raises concerns when conducting a codebase licensing audit. This codebase depends on Microsoft.DotNet.InternalAbstractions and so is also flagged as having a dependency on an "unlicensed" piece of software. Same goes for NUnit3TestAdapter which make use of NUnit.Engine - https://github.com/nunit/nunit3-vs-adapter/issues/785

It would be nice if the dependency was restricted to .Net Standard 1.6 only because this is the only case it is actually needed. This would greatly reduce impact of the licensing issue.

**Comment by CharliePoole** [comment]
In fact, it doesn't even seem that we do anything important with the value we get for clrVersion. It's added to the XML for a start-run event. The console doesn't seem to do anything with it. In any case, there are other cases where  the content of our events is reduced for 1.6, so it may be possible to drop the dependency entirely.

**Comment by Dmitry-Me** [comment]
@CharliePoole It looks like you already have plans to drop 1.6 https://github.com/nunit/nunit-console/issues/725

**Comment by CharliePoole** [comment]
Yes, but it's not entirely clear what that means yet... i.e. will users still have a way to run tests under 1.6 via older drivers, agents, etc. In any case, we wouldn't want master test runner to run under 1.6 because it runs in the process of the test runner itself.

**Comment by ChrisMaddock** [comment]
Nice detective work. @Dmitry-Me, we'd appreciate a PR for this if you'd be willing. 

As Charlie said, continuing support of 1.6 needs more thought. Let's just knock out the dependency for now, by restricting the nuspec dependency to 1.6 only.

**Comment by CharliePoole** [comment]
Even though I think future support for legacy agents needs to be discussed, I wonder why we need a 1.6 build for the engine assembly. After all, eliminating it was one of the main reasons for splitting the engine into two parts. IMO we still need to maintain an engine.core assembly under .NET Standard 1.6, but I don't see the point of an engine assembly, which would require a .Net Core 1.x runner in order to be useful.

The sole glitch I see is that we do release a 1.6 engine package and it's possible (but seems unlikely) that somebody is maintaining a third party runner that requires it. If we are worried about that, we could simply freeze it.

That said, I'm in favor of doing PRs that are small enough to require very little review and can be merged rapidly. :smiley:
