### ISSUE TITLE
Running tests in the server causes Nunit to hang

### ISSUE THREAD

**Issue by christosNik** [nunit/nunit-console#820]
Hi
Running Nunit causes it to hang with a debugger break.

The command:
C:\>D:\agent\_work\1\s\Libraries\pc\AnyCPU\NUnit\nunit-console.exe D:\agent\_work\1\s\SLIB\x64_vs150\Release\Slb.OneFluid.Shell.UnitTest.dll
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8813 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
..................................................................................

in the middle of the tests we get the dialog below which needs to be killed manually to continue the tests 
![nunit-agent-2020-10-15_11-03-44](https://user-images.githubusercontent.com/67835972/96109570-ae00a480-0ed6-11eb-8a60-05fe0c912312.png)

Is this a known issue? Any solutions?

Many thanks for your help!
Christos

**Comment by CharliePoole** [comment]
NUnit V2 is not maintained and has been archived for a number of years. There are several possibilities here and we will need more info in order to point you in the right direction.

1. You are trying to use NUnit V2 to test an application for which it was not designed, e.g. .NET Core. I doubt that since you ran a number of tests successfully before it failed. Even so, please tell us what platform your tests are targeting.

2. You encountered an old bug in NUnit V2, which was fixed in later releases. In that case, updating may fix the problem.

3. You encountered a new bug in NUnit V2. In that case it should be reported to the NUnit Legacy Project (see below).

4. You are using the NUnit 3 documentation and tried to make use of a feature that doesn't exist in NUnit V2. That could easily crash it, particularly with the 2.6.4 release.

5. You are actually intending to use NUnit 3 but downloaded the wrong package. I'm assuming that you would only be using NUnit V2 because you have old tests, which were never converted.

### Release Info

NUnit 2.6.4 was the last version of NUnit V2 released by the NUnit Project.

I created the NUnit Legacy Project at https://github.com/nunit-legacy/nunitv2 to continue some level of maintenance of V2 for those who need to keep using it. The latest release from that project is 2.7.1. 

Let's figure out which of the alternatives I listed applies here. If it seems appropriate I can transfer your issue to the legacy project.

**Comment by christosNik** [comment]
Thanks Charlie
Our target framework is .NET 4.6.1. Our tests had been running successfully for many years and this problem came up recently when we moved them to a new agent.

I had a quick look at our options 2.7.1 and 3.11. Both are incompatible with 2.6.4 that we are using,  (eg the class AssertionHelper not supported). Given that we are a mature product with a v.small team, I would tend to go for the 2.7.1 option, hoping it would require less refactoring on our side, let me know if you have any views on this.
Regards
Christos

**Comment by ChrisMaddock** [comment]
Hi @christosNik,

FYI there's a drop in replacement for AssertionHelper for NUnit 3.X, take a look at [NUnit.StaticExpect](https://github.com/fluffynuts/NUnit.StaticExpect) by @fluffynuts. If you did want to migrate to 3.x, you might also be interested in @wachulski's [NUnit migrator](https://github.com/wachulski/nunit-migrator) project, which provides Roslyn analysers to highlight and automate a lot of the changes that would be needed. 

I'm going to close this issue, as we no longer maintain v2 from this project. As Charlie said, he's continuing some maintenance over on the NUnit Legacy project, and that may be the best place to take this forward. 

Hope that helps!

**Comment by ChrisMaddock** [comment]
Oh - one more option. It's also possible to run your NUnit v2 tests through the NUnit v3 console - just make sure you have the [NUnit v2 driver extension](https://www.nuget.org/packages/NUnit.Extension.NUnitV2Driver/) installed. 

The main use for that would normally be when you have some NUnit 3 and some NUnit 2 test projects mixed in together, but given you're having problems with the NUnit Agent crashing, it might be worth a quick try with the v3 console, to see if that helps at all.
