### ISSUE TITLE
NUnit 3 - XmlResultWriter

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit-console#832]
Hi
By upgrading the nunit version to v3, I see that XmlResultWriter is missing.
Any suggestions?
Best Regards,
Nadeem Bader

**Comment by fossum** [comment]
@ChrisMaddock, I am tyrying to upgrade existing code to NUnit3 and also see the writer is missing. We are using the writer to save NUnit results output for CI tools. Is there a better way to do this? Or should I keep trying to look for a replacement?

**Comment by CharliePoole** [comment]
What exactly do you mean by the writer being missing? Are you refering to the NUnit V2 Result Writer Extension? (In fact, there are a number of different result writers, which create output in different formats)

Also... 
* What version of the console runner are you using?
* What command do you enter?
* What happens as a result?

The issue was closed because it appeared to be a misunderstanding on the part of the OP... but we can reopen if there's a real problem!
