### ISSUE TITLE
.NET Core console runner fails to load extensions when netfx and netstandard versions conflict

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#844]
It does not work when a file like "NUnit.Extension.TeamCityEventListener\1.0.9\tools\.addins" contains:
```
net20/
netstandard2.0/
```

It works when it contains:
```
netstandard2.0/
net20/
```

[InternalTrace.26616.log](https://github.com/nunit/nunit-console/files/5709755/InternalTrace.26616.log)

**Comment by ChrisMaddock** [comment]
There is a problem here with the engine's extension selecting logic. The initial 'ranking' of available extensions doesn't consider if an extension can be loaded on the current runtime or not, which is checked later in the process. Because that check isn't carried out early enough, it means that in certain situations and valid extension can be replaced with an invalid one, which can then be silently ignored, if discovered via addins file "wildcards" such as the above situation.
