### ISSUE TITLE
How can I list multiple tests to be run with --where filter 

### ISSUE THREAD

**Issue by desiGorcheva** [nunit/nunit-console#857]
Hi, I have created data driven tests and run them from Jenkins job. When some of them fail, I want to run only them. So I am calling the jenkins api and collecting the test names. 
The following command works perfect when there is one failed test:
**nunit3-console DataDrivenNUnit.dll --where "test =~ xxx1"**
But how can run multiple tests with one command? 
I have tried diff combinations, like: nunit3-console DataDrivenNUnit.dll --where "test =~ xxx1", --where "test =~ xxx2"
But is not working.
Thank you

**Comment by CharliePoole** [comment]
Try this...

```
--where "test=~xx1 || test=~xx2"
```

You may also use a single `|` or the word `or`.

**Comment by desiGorcheva** [comment]
I have tried with _or_, but mybe I got something wrong with the quotes in the command. 
This works perfect. 
Thank you!

**Comment by CharliePoole** [comment]
The purpose of the quotes is to force the operating system (Windows I assume) to treat the value as a __single__ argument. Using `or` without the quotes, the spaces cause it to be three arguments. Using `|` the character is taken to mean that the output should be piped to another program.

On Linux, a single quote `'` is often even better.

The main thing is to fully understand how the command-line works for your particular OS and shell, so that the console runner actually receives the option values you want it to have.
