### ISSUE TITLE
NUnitEngineException by updating from 3.11.1 to 3.12

### ISSUE THREAD

**Issue by MartinZec** [nunit/nunit-console#872]
I get the attached exception after updating NUnit-Console from 3.11.1 to 3.12.
With NUnit-Console 3.11.1, there was no exception thrown.

I have NUnit 3.13 installed via Visual Studio 2017 NuGet. 

[exception.txt](https://github.com/nunit/nunit-console/files/5835965/exception.txt)

**Comment by mikkelbu** [comment]
@MartinZec What is the targetframework in the test project and the production project?

**Comment by MartinZec** [comment]
I used .NET 4.8

**Comment by ChrisMaddock** [comment]
Hi @MartinZec - I can't reproduce this. Please can you add what command line you're using, an example of your csproj and include the debug logs from adding the --trace=Debug flag? If you're able to upload a project that reproduces this, that would be really helpful - thanks!

**Comment by MartinZec** [comment]
Hello,

I was able to reproduce, the issue happens in case the .dll is compiled in x86 platform configuration.
I used: "nunit3-console test1.test.test12 test.dll" with the attached project.

Best regards,
Martin
[test.zip](https://github.com/nunit/nunit-console/files/5841658/test.zip)

**Comment by CharliePoole** [comment]
@MartinZec What happens if you use `--x86` on the command-line?

**Comment by MartinZec** [comment]
@CharliePoole `nunit3-console test1.test.test12 test.dll --x86` give the same error as above mentioned

**Comment by CharliePoole** [comment]
@MartinZec In that case, it's probably not an error in detecting that the code is x86 but in how we use that info to run the agent. Can you ascertain which agent is running? (Put a  Sleep in a test if it's finishing too fast)

OTOH if you are running in process, then the bug is in allowing you to do that.

Is that command-line a typo? Is `test1.test.test12` a file?

**Comment by MartinZec** [comment]
@CharliePoole In taskmanager I see NUnit Agent (32bit)

**Comment by MartinZec** [comment]
attached the debug logs
[Uploading nunit-agent_14228.log…]
[InternalTrace.9784.log](https://github.com/nunit/nunit-console/files/5843025/InternalTrace.9784.log)

attached the debug logs
[nunit-agent_10720.log](https://github.com/nunit/nunit-console/files/5843023/nunit-agent_10720.log)

**Comment by CharliePoole** [comment]
@MartinZec From your logs, I see that you have some extensions installed and I'm wondering if they are failing to load in an x86 environment, causing the error you see. Can you run without extensions?

**Comment by ChrisMaddock** [comment]
Ahhh - think I've got it. The logs show a) that you're using the msi installation and b) that the .NET 4.0 x86 agent is somehow being launched on .NET 2.0. Thinking of the recent changes, that lead me to take a look at the msi installer, and looks like there's a copy/paste error affecting specifically the .NET 4.0 x86 agent - which will be why it wasn't caught in the manual testing before the release.

https://github.com/nunit/nunit-console/blob/a4274f86c24d3b84164cdb7c05eabda7d336a6e6/msi/nunit/engine-files.wxi#L79-L84

When I tried to repro yesterday, I was using a Chocolatey installation - the fact you were using the msi was the key piece here.

Gotta run now, but will try and get a fix out soon. Given it's just a packaging error, I think we can just rebuild and reupload the msi, rather than doing a full minor release. In the mean time - you should be able to avoid the problem by using the zip distribution. Or NuGet, or Chocolatey, or any other package other than the msi! 🙂

**Comment by ChrisMaddock** [comment]
I have temporarily removed the msi installer from the GitHub release until we resolve this issue.

**Comment by ChrisMaddock** [comment]
Resolved, and release updated. Thanks for flagging @MartinZec. 🙂
