### ISSUE TITLE
v4: Remove deprecated --params option

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#888]

**Comment by GitClickOk** [comment]
@ChrisMaddock, I see [here](https://docs.nunit.org/articles/nunit/release-notes/console-and-engine.html#nunit-console-310---march-24-2019) since the 3.10 version the `--params` option is deprecated in favor of `--testparam` option. Please, update the [docs](https://docs.nunit.org/articles/nunit/running-tests/Console-Command-Line.html) then, there is no reference to `--testparam` option. The deprecation note will be nice too.

PS: (If the docs are open source, and if you want I can try contribute and update myself)

**Comment by ChrisMaddock** [comment]
Hi @GitClickOk - a contribution to the docs would be really appreciated! Just click the "Improve this Doc" link in the top right of the page, which will take you to the relevant GitHub repo. 🙂 Let us know if you have any problems.

**Comment by GitClickOk** [comment]
@ChrisMaddock FYI I have created a PR for suggested change in the docs. I saw the markdown was broken in --param option and I have fixed too.

I hope is everything ok, this is the first time I create a PR in GitHub, I'm work only with BitBucket :)

**Comment by ChrisMaddock** [comment]
That looks great - thanks @GitClickOk! Appreciate the help! 😄

**Comment by CharliePoole** [comment]
@jnm2 @mikkelbu @rprouse 

Since we are breaking things for 4.0 anyway, my inclination is to use the syntax and implementation of --testParams but go back the original naming of --params. What do you think?

**Comment by jnm2** [comment]
I'm fine with it.

**Comment by rprouse** [comment]
I'm good with it too. Are we planning on using a different executable name for 4?

**Comment by CharliePoole** [comment]
I never thought about it but obviously nunit3-console isn't good any more! I'll make an issue.
