### ISSUE TITLE
Known Vulnerability in System.Xml.XPath.XmlDocument

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit-console#908]
`System.Xml.XPath.XmlDocument` 4.3.0 and other packages have a known security vulnerabilities and need to be updated to 4.3.1.

As reported by a user,

> We are using NUnit3TestAdapter package in some of our projects (.NET Core 3.1), which according to our latest security (whitesource) scans contains some vulnerabilities (System.Text.RegularExpressions 4.3.0). These policy vulnerabilities are coming from some packages that are used in your component, "System.Xml.XmlDocument 4.3.0", "System.Xml.XPath.XmlDocument 4.3.0" and so on. From what we know the solution will be to update the version of System.Text.RegularExpressions to 4.3.1.

**Comment by rprouse** [comment]
@OsirisTerje you will want to track this so that you can update the adapter with the new engine.

**Comment by CharliePoole** [comment]
Should we be adding some sort of security scan to our own builds?

**Comment by ChrisMaddock** [comment]
Interesting. There doesn't seem to actually be a later version of this package to upgrade to. I wonder if we actually need it, or if it's a was only needed for the earlier .NET Standard versions.

**Comment by OsirisTerje** [comment]
As soon as the engine fix is out, I'll update both the 3-series and the new 4-series.

**Comment by mikkelbu** [comment]
Will it help to use `System.Xml.XDocument` instead of `System.Xml.XmlDocument` ? (as `System.Xml.XmlDocument` states the following "Developers should prefer the classes in the System.Xml.XDocument package.").

That being said I would be nice to know exactly what kind of "security vulnerabilities" we are are talking about. The only I - quickly - could find was https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708 and it can be that 4.3.1 solves this, but I'm quite sure that regular expressions in general can take exponential time compared to the input. https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices also have 

> When using System.Text.RegularExpressions to process untrusted input, pass a timeout. A malicious user can provide input to RegularExpressions causing a Denial-of-Service attack.

**Comment by ChrisMaddock** [comment]
I've done some digging. Looks like when netstandard1.3 and netstandard2.0 builds were added at the same time, all dependencies were added for both builds. This one doesn't seem to be needed anymore since we've got rid of netstandard1.3 - PR incoming. 🙂
