### ISSUE TITLE
[Question] How can I create a TestPackage for an in-memory-only assembly?

### ISSUE THREAD

**Issue by stefanloerwald** [nunit/nunit-console#959]
Dear NUnit team / community,

I'm trying to set up an NUnit runner using the engine API (latest stable version). From reading the documentation, it should be just

```cs
var engine = NUnit.Engine.TestEngineActivator.CreateInstance();
var package = new NUnit.Engine.TestPackage("some.dll");
var runner = engine .GetRunner(package);
var results = runner.Run(listener: null, NUnit.Engine.TestFilter.Empty);
System.Console.WriteLine(results.OuterXml);
```

The issue I'm having here is line 2: creation of the `TestPackage`. The assembly containing the test methods is only compiled at runtime of the project, hence only exists in memory, not on disk. How can I load that assembly to run tests on it?

Thanks
Stefan

**Comment by CharliePoole** [comment]
Short answer: you can't - a TestPackage is basically a list of file names plus a dictionary of settings.

While we could modify TestPackage to allow a reference to an assembly already in memory, that can only happen with a new major release  (4.0) of the console, since TestPackage is part of the API assembly. @ChrisMaddock do we want to take this into account for 4.0?

Your best workaround for now is to write the assembly to a temporary file.

**Comment by stefanloerwald** [comment]
Thanks for the rapid reply, @CharliePoole! I got things to work with nunitlite, but wanted to get XML instead of just a blob of text. I'd very much love to see this API addition, but understand that it's a rather large thing which needs proper design.

Thanks and have a great weekend
Stefan

**Comment by CharliePoole** [comment]
@stefanloerwald Just so you know, nunitlite does support the `--result` option, which will create an XML file wherever you want it.

**Comment by CharliePoole** [comment]
Looks like this was answered a while back, so I'm closing it. For further followup, feel free to post comments here.
